/*
 * File: app/view/Sipas/kelas/Compact.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.kelas.Compact', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.sipas_kelas_compact',

    requires: [
        'SIPAS.view.Sipas.kelas.List',
        'SIPAS.view.Sipas.kelas.Treelist',
        'Ext.grid.Panel',
        'Ext.tab.Tab',
        'Ext.tree.Panel'
    ],

    languageable: true,
    languageMode: 'title',
    languageCode: 'kelas_list',
    title: 'Daftar Klasifikasi Surat',
    plain: true,
    tabPosition: 'bottom',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'sipas_kelas_list',
                    title: 'Tampilan Tabel'
                },
                {
                    xtype: 'sipas_kelas_treelist',
                    title: 'Tampilan Hirarki'
                }
            ]
        });

        me.callParent(arguments);
    }

});