/*
 * File: app/view/Sipas/bebas/trf/Prop.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.bebas.trf.Prop', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_bebas_trf_prop',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.ComboBox',
        'Ext.view.BoundList',
        'Ext.XTemplate',
        'Ext.button.Button'
    ],

    width: 400,
    layout: 'fit',
    title: 'Transfer Arsip',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    margin: '0 7 0 7',
                    bodyPadding: 10,
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Surat',
                            name: 'surat_model',
                            emptyText: 'Pilih Surat',
                            editable: false,
                            displayField: 'nama',
                            store: 'Sipas.bebas.trf.surat.Combo',
                            valueField: 'value'
                        },
                        {
                            xtype: 'combobox',
                            itemId: 'comboScope',
                            minWidth: 300,
                            fieldLabel: 'Unit',
                            emptyText: 'Pilih Unit',
                            editable: false,
                            displayField: 'unit_nama',
                            store: 'Sipas.surat.scope.Combo',
                            valueField: 'unit_id',
                            listConfig: {
                                xtype: 'boundlist',
                                itemSelector: 'div',
                                itemTpl: [
                                    '{unit_nama} <span style="color: gray">({unit_kode})</span>'
                                ]
                            }
                        },
                        {
                            xtype: 'combobox',
                            hidden: true,
                            itemId: 'comboTipe',
                            fieldLabel: 'Tipe Internal',
                            name: 'surat_itipe',
                            emptyText: 'Pilih Internal',
                            editable: false,
                            displayField: 'itipe_nama',
                            store: 'Sipas.itipe.Combo',
                            valueField: 'itipe_id'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            cls: 'x-btn-bordered x-btn-info',
                            itemId: 'btnImport',
                            text: 'TRANSFER'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});