/*
 * File: app/view/Sipas/disposisi/session/read/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.disposisi.session.read.Pane', {
    extend: 'Ext.container.ButtonGroup',
    alias: 'widget.sipas_disposisi_session_read_pane',

    requires: [
        'Ext.form.field.Display',
        'Ext.form.Basic'
    ],

    cls: 'sipas_surat_penyetujuan_info_pane',
    frame: false,
    padding: 3,
    title: 'Informasi Disposisi',
    columns: 1,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'displayfield',
                    renderer: function(value, displayField) {
                        if(value){
                            if (value.length > 27){
                                return value.substring(0,27)+'...';
                            }
                            else{
                                return value;
                            }
                        }else{
                            return '';
                        }
                    },
                    itemId: 'textfieldUnread',
                    width: 160,
                    fieldLabel: 'Perintah:',
                    labelAlign: 'top',
                    labelSeparator: ' ',
                    name: 'perintah_text',
                    fieldCls: 'x-form-field'
                },
                {
                    xtype: 'displayfield',
                    renderer: function(value, displayField) {
                        if(value){
                            if (value.length > 27){
                                return value.substring(0,27)+'...';
                            }
                            else{
                                return value;
                            }
                        }else{
                            return '';
                        }
                    },
                    itemId: 'textfieldRead',
                    width: 160,
                    fieldLabel: 'Tindakan:',
                    labelAlign: 'top',
                    labelSeparator: ' ',
                    name: 'aksi_text',
                    fieldCls: 'x-form-field'
                }
            ]
        });

        me.callParent(arguments);
    },

    constructor: function() {
                this.callParent(arguments);
                return Ext.applyIf(this,{
                    form: new Ext.form.Basic(this)
                });
    }

});