/*
 * File: app/view/Sipas/bebas/unit/List.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.bebas.unit.List', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.sipas_bebas_unit_list',

    requires: [
        'Ext.toolbar.Toolbar',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.view.BoundList',
        'Ext.XTemplate',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.grid.column.Action',
        'Ext.grid.column.CheckColumn',
        'Ext.grid.View'
    ],

    header: false,
    title: 'Unit',
    disableSelection: true,
    emptyText: 'Tidak ada Data',
    store: 'Sipas.bebas.unit.List',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    hidden: true,
                    items: [
                        {
                            xtype: 'label',
                            cls: 'alternative bold',
                            padding: 4,
                            text: 'Daftar Asisten '
                        }
                    ]
                },
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    itemId: 'toolbarUnit',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        }
                    },
                    items: [
                        {
                            xtype: 'combobox',
                            flex: 1,
                            cls: 'x-field-search',
                            itemId: 'fieldSearch',
                            width: '100%',
                            emptyText: 'Tambah unit',
                            enforceMaxLength: true,
                            hideTrigger: true,
                            anyMatch: true,
                            displayField: 'unit_nama',
                            forceSelection: true,
                            queryMode: 'local',
                            store: 'Sipas.bebas.unit.Combo',
                            valueField: 'unit_id',
                            listConfig: {
                                xtype: 'boundlist',
                                emptyText: 'Pencarian tidak ditemukan',
                                itemSelector: 'div',
                                itemTpl: [
                                    '{unit_nama} <span class="alternative">({unit_kode})</span>'
                                ]
                            }
                        },
                        {
                            xtype: 'button',
                            itemId: 'buttonManual',
                            text: 'Pilih Manual'
                        },
                        {
                            xtype: 'tbfill',
                            hidden: true
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'actioncolumn',
                    itemId: 'clmAction',
                    width: 36,
                    align: 'center',
                    menuDisabled: true,
                    items: [
                        {
                            action: 'removerecord',
                            iconCls: 'x-action-col-icon-bin'
                        }
                    ]
                },
                {
                    xtype: 'gridcolumn',
                    minWidth: 200,
                    width: 200,
                    sortable: true,
                    dataIndex: 'arsip_bagi_unit_nama',
                    text: 'Nama Unit',
                    flex: 1
                },
                {
                    xtype: 'checkcolumn',
                    itemId: 'clmTambah',
                    width: 100,
                    dataIndex: 'arsip_bagi_bolehtambah',
                    text: 'Tambah Berkas'
                },
                {
                    xtype: 'checkcolumn',
                    itemId: 'clmUbah',
                    width: 100,
                    dataIndex: 'arsip_bagi_bolehubah',
                    text: 'Ubah Berkas'
                },
                {
                    xtype: 'checkcolumn',
                    itemId: 'clmHapus',
                    width: 100,
                    dataIndex: 'arsip_bagi_bolehhapus',
                    text: 'Hapus Berkas'
                }
            ]
        });

        me.processSipasstafwakilList(me);
        me.callParent(arguments);
    },

    processSipasstafwakilList: function(config) {
        var filters = {
            ftype: 'filters',
            encode: true,
            local: true
        };

        if (! config.features) {
            config.features=filters;
        } else {
            config.features.push(filters);
        }

        return config;
    }

});