/*
 * File: app/view/Sipas/internal/masuk/agenda/transfer/Popup.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.internal.masuk.agenda.transfer.Popup', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_internal_masuk_agenda_transfer_popup',

    requires: [
        'SIPAS.view.Sipas.com.surat.Pane',
        'SIPAS.view.Sipas.com.surat.pembuat.Pane',
        'SIPAS.view.Sipas.com.button.Process',
        'SIPAS.view.Sipas.com.button.View',
        'Ext.form.Panel',
        'Ext.form.field.Display',
        'Ext.form.FieldSet',
        'Ext.form.field.Date',
        'Ext.form.field.TextArea',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.view.BoundList',
        'Ext.XTemplate',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    hidden: false,
    width: 500,
    layout: 'fit',
    title: 'Transfer Masuk Internal ke Keluar Eksternal',
    maximizable: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    margin: '0 5 0 5',
                    width: 300,
                    bodyPadding: 10,
                    collapsible: true,
                    header: false,
                    title: 'Info Surat',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            languageable: true,
                            languageCode: 'imasuk_trf_desc_popup',
                            languageMode: 'value',
                            flex: 1,
                            value: ''
                        },
                        {
                            xtype: 'container',
                            layout: 'anchor',
                            items: [
                                {
                                    xtype: 'sipas_com_surat_pane',
                                    associated: true,
                                    border: false
                                },
                                {
                                    xtype: 'sipas_com_surat_pembuat_pane',
                                    associated: true,
                                    border: false,
                                    hidden: true
                                },
                                {
                                    xtype: 'fieldset',
                                    hidden: true,
                                    collapsible: true,
                                    title: 'Detail Surat',
                                    items: [
                                        {
                                            xtype: 'triggerfield',
                                            anchor: '100%',
                                            name: 'surat_nomor',
                                            emptyText: 'Pilih Agenda Masuk Internal ',
                                            editable: false
                                        },
                                        {
                                            xtype: 'container',
                                            height: 15
                                        },
                                        {
                                            xtype: 'datefield',
                                            anchor: '100%',
                                            itemId: 'txtTanggal',
                                            fieldLabel: 'Tgl.Surat',
                                            name: 'surat_tanggal',
                                            readOnly: true,
                                            format: 'd M Y H:i'
                                        },
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            itemId: 'txtPerihal',
                                            fieldLabel: 'Perihal',
                                            name: 'surat_perihal',
                                            readOnly: true,
                                            rows: 3
                                        },
                                        {
                                            xtype: 'container',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'txtPenerima',
                                                    width: 150,
                                                    fieldLabel: 'Pembuat',
                                                    labelAlign: 'top',
                                                    labelWidth: 75,
                                                    name: 'surat_properti_pembuat_nama',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'textfield',
                                                    flex: 1,
                                                    itemId: 'txtUnitkerja',
                                                    width: 150,
                                                    fieldLabel: 'Unit Kerja',
                                                    labelAlign: 'top',
                                                    labelWidth: 75,
                                                    name: 'surat_properti_pembuat_unit_nama',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            height: 15
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'surat_tujuan'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'surat_perihal'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'surat_agenda'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'surat_nomor'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'kelas_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'jenis_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'prioritas_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'prioritas_hari'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'lokasi_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'sifat_id'
                                        },
                                        {
                                            xtype: 'hiddenfield',
                                            anchor: '100%',
                                            fieldLabel: 'Label',
                                            name: 'media_id'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'Label',
                                    name: 'korespondensi_kode'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'Label',
                                    name: 'surat_korespondensi'
                                },
                                {
                                    xtype: 'textfield',
                                    anchor: '100%',
                                    hidden: true,
                                    fieldLabel: 'Label',
                                    name: 'surat_korespondensi_surat'
                                },
                                {
                                    xtype: 'fieldset',
                                    itemId: 'transferKe',
                                    title: 'Transfer surat ke unit :',
                                    items: [
                                        {
                                            xtype: 'combobox',
                                            associated: true,
                                            anchor: '100%',
                                            itemId: 'suratUnit',
                                            margin: '0 0 0 2',
                                            afterSubTpl: [
                                                'Pilih unit yang akan menerima hasil transfer surat'
                                            ],
                                            name: 'surat_unit',
                                            allowBlank: false,
                                            editable: false,
                                            displayField: 'unit_nama',
                                            store: 'Sipas.surat.scope.Combo',
                                            valueField: 'unit_id',
                                            listConfig: {
                                                xtype: 'boundlist',
                                                itemSelector: 'div',
                                                itemTpl: [
                                                    '{unit_nama} <span class="alternative">({unit_kode})</span>'
                                                ]
                                            }
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            padding: '10 0 0 0',
                                            name: 'surat_arsip',
                                            value: 1,
                                            afterBoxLabelTpl: [
                                                '<div class="margin-left-24">Berkas pada surat ini akan ikut ditransfer</div>'
                                            ],
                                            boxLabel: 'Transfer berkas surat',
                                            inputValue: '1',
                                            uncheckedValue: '0'
                                        },
                                        {
                                            xtype: 'checkboxfield',
                                            anchor: '100%',
                                            hidden: true,
                                            name: 'surat_korespondensi',
                                            value: 1,
                                            boxLabel: 'Korespondensi Surat',
                                            inputValue: '1',
                                            uncheckedValue: '0'
                                        },
                                        {
                                            xtype: 'container',
                                            margin: '20 0 0 0',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch',
                                                defaultMargins: {
                                                    top: 4,
                                                    right: 0,
                                                    bottom: 6,
                                                    left: 0
                                                },
                                                pack: 'end'
                                            },
                                            items: [
                                                {
                                                    xtype: 'sipas_com_button_process',
                                                    cls: 'x-btn-bordered x-btn-info',
                                                    text: 'Mulai Transfer',
                                                    margins: '4 4 8 4'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    itemId: 'transferSukses',
                                    layout: 'anchor',
                                    items: [
                                        {
                                            xtype: 'fieldset',
                                            title: 'Hasil transfer surat',
                                            layout: {
                                                type: 'hbox',
                                                align: 'stretch'
                                            },
                                            items: [
                                                {
                                                    xtype: 'displayfield',
                                                    flex: 1,
                                                    itemId: 'infoHasilTransfer'
                                                },
                                                {
                                                    xtype: 'sipas_com_button_view',
                                                    itemId: 'hasilSurat',
                                                    margin: '4 4 8 4',
                                                    ui: 'default-toolbar',
                                                    text: 'Lihat Hasil Surat'
                                                },
                                                {
                                                    xtype: 'container',
                                                    hidden: true,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'stretch'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'displayfield',
                                                            flex: 1,
                                                            itemId: 'infoSuratHasilTransfer'
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            layout: {
                                                                type: 'hbox',
                                                                align: 'bottom',
                                                                pack: 'end'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});