/*
 * File: app/view/Sipas/beranda/board/notification/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.beranda.board.notification.Pane', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.sipas_beranda_board_notification_pane',

    requires: [
        'SIPAS.view.Sipas.com.button.Refresh',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.TextItem',
        'Ext.toolbar.Fill',
        'Ext.button.Button',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.grid.feature.Grouping',
        'Ext.XTemplate'
    ],

    header: false,
    title: 'Notifikasi Belum Dibaca dan Belum Ditanggapi',
    emptyText: 'Tidak ada Data',
    hideHeaders: true,
    store: 'Sipas.beranda.notification.List',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 8,
                            left: 4
                        }
                    },
                    items: [
                        {
                            xtype: 'tbtext',
                            text: '<b style="color:#04408c">Belum dibaca dan ditanggapi<b>'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'sipas_com_button_refresh'
                        }
                    ]
                }
            ],
            columns: [
                {
                    xtype: 'datecolumn',
                    hidden: true,
                    width: 120,
                    sortable: true,
                    dataIndex: 'notification_tanggal',
                    menuDisabled: true,
                    text: 'Tgl.Terima',
                    format: 'd M Y H:i'
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        var notif_kode = record.get('notification_kelompok_kode'),
                        // notif_tgl = Ext.util.Format.date(record.get('notification_tanggal'), 'd M Y H:i'),
                            notif_tgl = record.getDateFormat(),
                            notif_pengirim = record.get('notification_pengirim'),
                            notif_record = record.get('notification_record'),
                            notif_perihal = value,
                            surat_nomor = notif_record.surat_nomor,
                            surat_jenis = record.get('notification_jenis'),
                            surat_prioritas = record.get('notification_prioritas'),
                            surat_model = notif_record.surat_model,
                            sifat_kode = notif_record.sifat_kode,
                            sifat_color = notif_record.sifat_color,
                            sifat_label = '',
                            notif = '';

                        if (!value || value === null || value === ''){
                            notif_perihal = '<span class="alternative">(Tidak ada perihal)</span>';
                        }

                        if (!surat_nomor || surat_nomor === null || surat_nomor === ''){
                            surat_nomor = '<span class="alternative">(Tidak ada nomor surat)</span>';
                        }

                        if (!surat_jenis || surat_jenis === null || surat_jenis === ''){
                            surat_jenis = '<span class="alternative">(Tidak ada jenis surat)</span>';
                        }

                        if (!surat_prioritas || surat_prioritas === null || surat_prioritas === ''){
                            surat_prioritas = '<span class="alternative">(Tidak ada prioritas)</span>';
                        }

                        if (sifat_color){
                            sifat_label = '<span class="badge badge-light margin-right-4" style="background-color:'+sifat_color+';">'+sifat_kode+'</span>';
                        }

                        if (notif_kode === 'disposisi'){
                            return new Ext.XTemplate([
                            '<span style="float:right;" class="supporttext alternative">{notif_tgl}</span>'+
                            '<div class="cell-visual cell-visual-left" data-qtip="Pengirim">'+
                            '<img class="img img-circle img-32" src="server.php/sipas/staf/get_image/foto?id={id}">'+
                            '</div>'+
                            '<div class="cell-text">'+
                            '<div class="subtext" data-qtip="Nama pengirim">{pengirim}</div>'+
                            '<div class="supporttext" data-qtip="Perihal surat">{sifat_label}{surat_perihal}</div>'+
                            '<div class="supporttext margin-top-4">'+
                            '<span class="margin-right-8" data-qtip="Jenis surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-pricetag grey-500-i"></i>'+
                            '</span>{surat_jenis}'+
                            '</span>'+
                            '<span data-qtip="Prioritas surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-alert grey-500-i"></i>'+
                            '</span>{surat_prioritas}'+
                            '</span>'+
                            '</div>'+
                            '</div>'
                            ]).apply({
                                id: notif_record.disposisi_pengirim_id,
                                pengirim: notif_record.disposisi_pengirim_nama,
                                surat_perihal: notif_perihal,
                                surat_jenis: surat_jenis,
                                surat_prioritas: surat_prioritas,
                                sifat_label: sifat_label,
                                notif_tgl: notif_tgl
                            });
                        } else if (notif_kode === 'notadinas'){
                            return new Ext.XTemplate([
                            '<span style="float:right;" class="supporttext alternative">{notif_tgl}</span>'+
                            '<div class="cell-visual cell-visual-left" data-qtip="Pengirim">'+
                            '<img class="img img-circle img-32" src="server.php/sipas/staf/get_image/foto?id={id}">'+
                            '</div>'+
                            '<div class="cell-text">'+
                            '<div class="subtext" data-qtip="Nama pengirim">{pengirim}</div>'+
                            '<div class="supporttext" data-qtip="Perihal surat">{sifat_label}{surat_perihal}</div>'+
                            '<div class="supporttext margin-top-4">'+
                            '<span class="margin-right-8" data-qtip="Jenis surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-pricetag grey-500-i"></i>'+
                            '</span>{surat_jenis}'+
                            '</span>'+
                            '<span data-qtip="Prioritas surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-alert grey-500-i"></i>'+
                            '</span>{surat_prioritas}'+
                            '</span>'+
                            '</div>'+
                            '</div>'
                            ]).apply({
                                id: notif_record.disposisi_pengirim_id,
                                pengirim: notif_record.disposisi_pengirim_nama,
                                surat_perihal: notif_perihal,
                                surat_jenis: surat_jenis,
                                surat_prioritas: surat_prioritas,
                                sifat_label: sifat_label,
                                notif_tgl: notif_tgl
                            });
                        } else if (notif_kode === 'koreksi'){
                            return new Ext.XTemplate([
                            '<span style="float:right;" class="supporttext alternative">{notif_tgl}</span>'+
                            '<div class="cell-visual cell-visual-left" data-qtip="Pengirim">'+
                            '<img class="img img-circle img-32" src="server.php/sipas/staf/get_image/foto?id={id}">'+
                            '</div>'+
                            '<div class="cell-text">'+
                            '<div class="subtext" data-qtip="Nama pengirim">{pengirim}</div>'+
                            '<div class="supporttext" data-qtip="Perihal surat">{sifat_label}{surat_perihal}</div>'+
                            '<div class="supporttext margin-top-4">'+
                            '<span class="margin-right-8" data-qtip="Jenis surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-pricetag grey-500-i"></i>'+
                            '</span>{surat_jenis}'+
                            '</span>'+
                            '<span data-qtip="Prioritas surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-alert grey-500-i"></i>'+
                            '</span>{surat_prioritas}'+
                            '</span>'+
                            '</div>'+
                            '</div>'
                            ]).apply({
                                id: notif_record.disposisi_pengirim_id,
                                pengirim: notif_record.disposisi_pengirim_nama,
                                surat_perihal: notif_perihal,
                                surat_jenis: surat_jenis,
                                surat_prioritas: surat_prioritas,
                                sifat_label: sifat_label,
                                notif_tgl: notif_tgl
                            });
                        } else if (notif_kode === 'koreksi_status'){
                            var setuju = notif_record.surat_setuju,
                                r_setuju = '',
                                penyetuju = record.get('notification_penyetuju');

                            if (setuju === '1'){
                                r_setuju = '<span class="margin-left-8 warning"><span class="badge badge-solid margin-right-4"><i class="icon ion-md-warning"></i></span>Dalam proses</span>';
                            } else if (setuju === '2'){
                                r_setuju = '<span class="margin-left-8 info"><span class="badge badge-solid margin-right-4"><i class="icon ion-md-checkmark"></i></span>Disetujui</span>';
                            } else if (setuju === '3'){
                                r_setuju = '<span class="margin-left-8 danger"><span class="badge badge-solid margin-right-4"><i class="icon ion-md-close"></i></span>Revisi</span>';
                            } else if (setuju === '4'){
                                r_setuju = '<span class="margin-left-8 danger"><span class="badge badge-solid margin-right-4"><i class="icon ion-md-close"></i></span>Ditolak</span>';
                            } else {
                                r_setuju = '<span class="margin-left-8 alternative">Unknown</span>';
                            }

                            return new Ext.XTemplate([
                            '<span style="float:right;" class="supporttext alternative">{notif_tgl}</span>'+
                            '<div class="cell-visual cell-visual-left" data-qtip="Penyetuju">'+
                            '<img class="img img-circle img-32" src="server.php/sipas/staf/get_image/foto?id={id}">'+
                            '</div>'+
                            '<div class="cell-text">'+
                            '<div class="subtext" data-qtip="Nama penyetuju">{penyetuju}{setuju}</div>'+
                            '<div class="supporttext" data-qtip="Perihal surat">{sifat_label}{surat_perihal}</div>'+
                            '<div class="supporttext margin-top-4">'+
                            '<span class="margin-right-8" data-qtip="Jenis surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-pricetag grey-500-i"></i>'+
                            '</span>{surat_jenis}'+
                            '</span>'+
                            '<span data-qtip="Prioritas surat">'+
                            '<span class="badge badge-solid margin-right-4">'+
                            '<i class="icon ion-md-alert grey-500-i"></i>'+
                            '</span>{surat_prioritas}'+
                            '</span>'+
                            '</div>'+
                            '</div>'
                            ]).apply({
                                id: penyetuju.staf_id,
                                penyetuju: penyetuju.staf_nama,
                                surat_perihal: notif_perihal,
                                surat_jenis: surat_jenis,
                                surat_prioritas: surat_prioritas,
                                notif_tgl: notif_tgl,
                                sifat_label: sifat_label,
                                setuju: r_setuju
                            });
                        } else {
                            // Surat masuk

                            if (surat_model === '1' || surat_model === '2'){
                                // Eksternal
                                var tpl = new Ext.XTemplate([
                                '<span style="float:right;" class="supporttext alternative">{notif_tgl}</span>'+
                                '<div class="cell-visual cell-visual-left" data-qtip="{jenis_surat}">'+
                                '<div class="img img-circle img-36">'+
                                '<i class="bigger-1-25 icon ion-md-mail grey-600-i"></i>'+
                                '</div>'+
                                '</div>'+
                                '<div class="cell-text">'+
                                '<div class="subtext" data-qtip="Nama pengirim">{pengirim}</div>'+
                                '<div class="supporttext" data-qtip="Perihal surat">{sifat_label}{perihal}</div>'+
                                '<div class="supporttext margin-top-4">'+
                                '<span class="margin-right-8" data-qtip="Jenis surat">'+
                                '<span class="badge badge-solid margin-right-4">'+
                                '<i class="icon ion-md-pricetag grey-500-i"></i>'+
                                '</span>{surat_jenis}'+
                                '</span>'+
                                '<span data-qtip="Prioritas surat">'+
                                '<span class="badge badge-solid margin-right-4">'+
                                '<i class="icon ion-md-alert grey-500-i"></i>'+
                                '</span>{surat_prioritas}'+
                                '</span>'+
                                '</div>'+
                                '</div>'
                                ]).apply({
                                    perihal: notif_perihal,
                                    pengirim: record.get('notification_pengirim'),
                                    jenis_surat : 'Surat Masuk Eksternal',
                                    surat_jenis: surat_jenis,
                                    surat_prioritas: surat_prioritas,
                                    sifat_label: sifat_label,
                                    notif_tgl: notif_tgl
                                });
                            } else if (surat_model === '3' || surat_model === '4'){
                                // Internal
                                var tpl = new Ext.XTemplate([
                                '<span style="float:right;" class="supporttext alternative">{notif_tgl}</span>'+
                                '<div class="cell-visual cell-visual-left" data-qtip="Pengirim">'+
                                '<img class="img img-circle img-36" src="server.php/sipas/staf/get_image/foto?id={id}">'+
                                '</div>'+
                                '<div class="cell-text">'+
                                '<div class="subtext" data-qtip="Nama pengirim">{pengirim_nama}</div>'+
                                '<div class="supporttext" data-qtip="Perihal surat">{sifat_label}{perihal}</div>'+
                                '<div class="supporttext margin-top-4">'+
                                '<span class="margin-right-8" data-qtip="Jenis surat">'+
                                '<span class="badge badge-solid margin-right-4">'+
                                '<i class="icon ion-md-pricetag grey-500-i"></i>'+
                                '</span>{surat_jenis}'+
                                '</span>'+
                                '<span data-qtip="Prioritas surat">'+
                                '<span class="badge badge-solid margin-right-4">'+
                                '<i class="icon ion-md-alert grey-500-i"></i>'+
                                '</span>{surat_prioritas}'+
                                '</span>'+
                                '</div>'+
                                '</div>'
                                ]).apply({
                                    id: notif_record.disposisi_pengirim_id,
                                    perihal: notif_perihal,
                                    surat_nomor: surat_nomor,
                                    surat_prioritas: surat_prioritas,
                                    pengirim_nama: notif_record.disposisi_pengirim_nama,
                                    jenis_surat : 'Surat Masuk Internal',
                                    surat_jenis: surat_jenis,
                                    sifat_label: sifat_label,
                                    notif_tgl: notif_tgl
                                });
                            }

                            return tpl;
                        }
                    },
                    sortable: true,
                    dataIndex: 'notification_perihal',
                    menuDisabled: true,
                    text: 'Perihal',
                    flex: 2
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if(value !== null){
                            return value;
                            //     return '<div style="white-space:normal !important;">'+ Ext.util.Format.ellipsis(value,20) +'</div>';
                        }else{
                            return '<span style="color:lightgray;">Tidak ada pengirim</span>';
                        }
                    },
                    hidden: true,
                    sortable: true,
                    dataIndex: 'notification_pengirim',
                    menuDisabled: true,
                    text: 'Dari',
                    flex: 1
                }
            ],
            features: [
                {
                    ftype: 'grouping',
                    groupHeaderTpl: [
                        '{name}'
                    ],
                    hideGroupedHeader: true
                }
            ]
        });

        me.callParent(arguments);
    }

});