/*
 * File: app/view/Sipas/com/surat/korespondensi/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.com.surat.korespondensi.Pane', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.sipas_com_surat_korespondensi_pane',

    requires: [
        'SIPAS.view.Sipas.com.button.Cross',
        'SIPAS.view.Sipas.com.button.View',
        'SIPAS.view.Sipas.com.button.Correspondent',
        'SIPAS.view.Sipas.com.button.Putin',
        'SIPAS.view.Sipas.com.button.Close',
        'Ext.form.FieldContainer',
        'Ext.form.field.Hidden',
        'Ext.form.field.Trigger',
        'Ext.button.Button',
        'Ext.form.field.TextArea',
        'Ext.form.field.Display'
    ],

    propType: 'default',
    title: 'Korespondensi Surat',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'fieldcontainer',
                    hidden: true,
                    itemId: 'containerChooser',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'hiddenfield',
                            flex: 1,
                            fieldLabel: 'Label',
                            name: 'surat_korespondensi_surat'
                        },
                        me.processKorespondensi_surat_agenda({
                            xtype: 'triggerfield',
                            propType: 'default',
                            flex: 1,
                            fieldLabel: 'No. Agenda',
                            labelWidth: 150,
                            name: 'korespondensi_surat_agenda',
                            editable: false
                        }),
                        {
                            xtype: 'sipas_com_button_cross',
                            listeners: {
                                afterrender: {
                                    fn: me.onButtonAfterRender,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'fieldcontainer',
                    hidden: true,
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'hiddenfield',
                            flex: 1,
                            fieldLabel: 'Label',
                            name: 'surat_korespondensi'
                        },
                        {
                            xtype: 'textfield',
                            flex: 1,
                            fieldLabel: 'No. Surat',
                            labelWidth: 120,
                            name: 'korespondensi_surat_nomor',
                            readOnly: true
                        },
                        {
                            xtype: 'sipas_com_button_view',
                            hidden: true,
                            text: 'Lihat Surat'
                        }
                    ]
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Instansi Pengirim',
                    labelWidth: 120,
                    name: 'korespondensi_pengirim',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Instansi Penerima',
                    labelWidth: 120,
                    name: 'korespondensi_penerima',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Unit Pengirim',
                    labelWidth: 120,
                    name: 'korespondensi_unitpengirim',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Unit Penerima',
                    labelWidth: 120,
                    name: 'korespondensi_unitpenerima',
                    readOnly: true
                },
                {
                    xtype: 'textfield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Kode Korespondensi',
                    labelWidth: 120,
                    name: 'korespondensi_nomor',
                    readOnly: true
                },
                {
                    xtype: 'textareafield',
                    anchor: '100%',
                    hidden: true,
                    fieldLabel: 'Perihal Korespondensi',
                    labelWidth: 120,
                    name: 'korespondensi_surat_perihal',
                    readOnly: true,
                    rows: 2
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    name: 'korespondensi_info'
                },
                {
                    xtype: 'displayfield',
                    anchor: '100%',
                    hidden: true,
                    name: 'korespondensi_info_internal'
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        padding: '0 0 0 45'
                    },
                    items: [
                        {
                            xtype: 'button',
                            languageCode: 'surat_atur_korespondensi',
                            languageMode: 'text',
                            languageable: true,
                            featureable: true,
                            featureName: 'surat_atur_korespondensi',
                            roleName: 'surat_atur_korespondensi',
                            roleable: true,
                            cls: 'x-btn-bordered',
                            itemId: 'buttonAturKorespondensi',
                            ui: 'default-toolbar',
                            text: 'Atur Korespondensi'
                        },
                        {
                            xtype: 'sipas_com_button_correspondent',
                            action: 'korespondensi',
                            roleable: true,
                            roleName: 'masuk_korespondensi',
                            featureable: true,
                            featureName: 'korespondensi',
                            cls: 'x-btn-bordered',
                            text: 'Lihat Korespondensi'
                        },
                        me.processPilihKorespondensi({
                            xtype: 'sipas_com_button_putin',
                            itemId: 'pilihKorespondensi',
                            margin: '0 5 0 0'
                        }),
                        me.processResetKorespondensi({
                            xtype: 'sipas_com_button_close',
                            cls: 'x-btn-bordered',
                            itemId: 'resetKorespondensi',
                            ui: 'default-toolbar',
                            text: 'RESET'
                        })
                    ]
                }
            ]
        });

        me.processSipascomsuratkorespondensiPane(me);
        me.callParent(arguments);
    },

    processKorespondensi_surat_agenda: function(config) {
        config.propType = this.propType;
        return config;
    },

    processPilihKorespondensi: function(config) {
        config.propType = this.propType;
        return config;
    },

    processResetKorespondensi: function(config) {
        config.propType = this.propType;
        return config;
    },

    processSipascomsuratkorespondensiPane: function(config) {
        config.propType = this.propType;
        return config;
    },

    onButtonAfterRender: function(component, eOpts) {
        var combo = component.prev('combobox,triggerfield');
        if(combo.readOnly){
            component.up('container').on('afterrender', function(parent){
                parent.remove(component);
            });
        }
    }

});