/*
 * File: app/model/Sipas/Disposisi.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.Disposisi', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field',
        'Ext.data.association.HasOne',
        'Ext.data.association.HasMany'
    ],
    uses: [
        'SIPAS.model.Sipas.Surat',
        'SIPAS.model.Sipas.disposisi.Masuk',
        'SIPAS.model.Sipas.Staf'
    ],

    statics: {
        retractedStatus: function() {
            return{
                AKTIF: 0,
                CABUT: 1
            };
        },

        renderPrioritas: function(useprioritas, prioritas_tgl, aksi) {
            if(useprioritas === "1" && !Ext.isEmpty(prioritas_tgl)){
                var tanggal = new Date(),
                    prioritas_tgl = prioritas_tgl,
                    tanggal_display = Ext.util.Format.date(prioritas_tgl, 'd M Y');

                prioritas_tgl.setHours(0,0,0,0);
                tanggal.setHours(0,0,0,0);
                var isprioritas = (prioritas_tgl < tanggal)? 1 : 0;

                if(isprioritas){
                    if(aksi){
                        return '<span>Sudah ada tindakkan</span>';
                    }else{
                        return '<span class="badge badge-solid margin-right-4"><i class="icon ion-md-calendar red-600-i"></i></span><span class="red">Sampai '+tanggal_display+'</span>';
                    }
                }else{
                    if(aksi){
                        return '<span>Sudah ada tindakkan</span>';
                    }else{
                        return '<span class="badge badge-solid margin-right-4"><i class="icon ion-md-calendar red-600-i"></i></span><span>Sampai '+tanggal_display+'</span>';
                    }
                }
            }else{
                return '<span class="alternative">(Tanpa Urgensi)</span>';
            }
        }
    },

    idProperty: 'disposisi_id',

    proxy: {
        type: 'ajax',
        api: {
            create: 'server.php/sipas/disposisi/create',
            read: 'server.php/sipas/disposisi/read',
            update: 'server.php/sipas/disposisi/update',
            destroy: 'server.php/sipas/disposisi/destroy'
        },
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    fields: [
        {
            name: 'disposisi_id'
        },
        {
            name: 'disposisi_staf'
        },
        {
            name: 'disposisi_profil'
        },
        {
            name: 'disposisi_pelaku'
        },
        {
            name: 'disposisi_pelaku_profil'
        },
        {
            name: 'disposisi_pulih_staf'
        },
        {
            name: 'disposisi_surat'
        },
        {
            name: 'disposisi_perintah'
        },
        {
            name: 'disposisi_induk'
        },
        {
            name: 'disposisi_model'
        },
        {
            name: 'disposisi_nomor'
        },
        {
            name: 'disposisi_tgl',
            type: 'date'
        },
        {
            name: 'disposisi_pesan'
        },
        {
            name: 'disposisi_istunggal',
            type: 'int'
        },
        {
            name: 'disposisi_israhasia',
            type: 'boolean'
        },
        {
            name: 'disposisi_isbaca',
            type: 'int'
        },
        {
            name: 'disposisi_baca_tgl',
            type: 'date'
        },
        {
            name: 'disposisi_iscabut',
            type: 'int'
        },
        {
            name: 'disposisi_cabut_tgl',
            type: 'date'
        },
        {
            name: 'disposisi_ispulih',
            type: 'int'
        },
        {
            name: 'disposisi_pulih_tgl',
            type: 'date'
        },
        {
            name: 'disposisi_cabut_induk'
        },
        {
            name: 'disposisi_properti'
        },
        {
            name: 'disposisi_pengirim_id'
        },
        {
            name: 'disposisi_pengirim_kode'
        },
        {
            name: 'disposisi_pengirim_nama'
        },
        {
            name: 'disposisi_pengirim_unit'
        },
        {
            name: 'disposisi_pengirim_isaktif',
            type: 'int'
        },
        {
            name: 'disposisi_pengirim_unit_nama'
        },
        {
            name: 'disposisi_pengirim_jabatan'
        },
        {
            name: 'disposisi_pengirim_jabatan_nama'
        },
        {
            name: 'disposisi_pelaku_id'
        },
        {
            name: 'disposisi_pelaku_kode'
        },
        {
            name: 'disposisi_pelaku_nama'
        },
        {
            name: 'disposisi_pelaku_unit'
        },
        {
            name: 'disposisi_pelaku_isaktif',
            type: 'int'
        },
        {
            name: 'disposisi_pelaku_unit_nama'
        },
        {
            name: 'disposisi_pelaku_jabatan'
        },
        {
            name: 'disposisi_pelaku_jabatan_nama'
        },
        {
            name: 'disposisi_pemulih_id'
        },
        {
            name: 'disposisi_pemulih_kode'
        },
        {
            name: 'disposisi_pemulih_nama'
        },
        {
            name: 'disposisi_pemulih_unit'
        },
        {
            name: 'disposisi_pemulih_isaktif',
            type: 'int'
        },
        {
            name: 'disposisi_pemulih_unit_nama'
        },
        {
            name: 'disposisi_pemulih_jabatan'
        },
        {
            name: 'disposisi_pemulih_jabatan_nama'
        },
        {
            name: 'surat_id'
        },
        {
            name: 'surat_arsip'
        },
        {
            name: 'surat_model'
        },
        {
            name: 'surat_model_sub'
        },
        {
            name: 'surat_itipe'
        },
        {
            name: 'surat_registrasi'
        },
        {
            name: 'surat_nomor'
        },
        {
            name: 'surat_agenda'
        },
        {
            name: 'surat_agenda_sub'
        },
        {
            name: 'surat_tanggal',
            type: 'date'
        },
        {
            name: 'surat_perihal'
        },
        {
            name: 'surat_pengirim'
        },
        {
            name: 'surat_tujuan'
        },
        {
            name: 'surat_lampiran'
        },
        {
            name: 'surat_ringkasan'
        },
        {
            name: 'surat_catatan'
        },
        {
            name: 'surat_korespondensi'
        },
        {
            name: 'surat_korespondensi_surat'
        },
        {
            name: 'surat_lokasi'
        },
        {
            name: 'surat_kelas'
        },
        {
            name: 'surat_jenis'
        },
        {
            name: 'surat_sifat'
        },
        {
            name: 'surat_media'
        },
        {
            name: 'surat_prioritas'
        },
        {
            name: 'surat_retensi'
        },
        {
            name: 'surat_useretensi'
        },
        {
            name: 'surat_properti'
        },
        {
            name: 'surat_unit'
        },
        {
            name: 'surat_setuju'
        },
        {
            name: 'surat_setuju_tgl',
            type: 'date'
        },
        {
            name: 'surat_setuju_isurut',
            type: 'int'
        },
        {
            name: 'surat_setuju_staf'
        },
        {
            name: 'surat_setuju_profil'
        },
        {
            name: 'surat_petikan_setuju'
        },
        {
            name: 'surat_petikan_akhir_staf'
        },
        {
            name: 'surat_petikan_setuju_isurut',
            type: 'int'
        },
        {
            name: 'surat_distribusi_tgl',
            type: 'date'
        },
        {
            name: 'surat_distribusi_staf'
        },
        {
            name: 'surat_distribusi_profil'
        },
        {
            name: 'surat_selesai_tgl',
            type: 'date'
        },
        {
            name: 'surat_selesai_staf'
        },
        {
            name: 'surat_selesai_profil'
        },
        {
            name: 'surat_terima_staf'
        },
        {
            name: 'unit_id'
        },
        {
            name: 'unit_kode'
        },
        {
            name: 'unit_nama'
        },
        {
            name: 'media_id'
        },
        {
            name: 'media_nama'
        },
        {
            name: 'media_kode'
        },
        {
            name: 'media_isaktif',
            type: 'int'
        },
        {
            name: 'media_properti'
        },
        {
            name: 'prioritas_id'
        },
        {
            name: 'prioritas_kode'
        },
        {
            name: 'prioritas_nama'
        },
        {
            name: 'prioritas_retensi'
        },
        {
            name: 'prioritas_isaktif',
            type: 'int'
        },
        {
            name: 'prioritas_properti'
        },
        {
            name: 'jenis_id'
        },
        {
            name: 'jenis_nama'
        },
        {
            name: 'jenis_kode'
        },
        {
            name: 'jenis_isaktif',
            type: 'int'
        },
        {
            name: 'jenis_properti'
        },
        {
            name: 'sifat_id'
        },
        {
            name: 'sifat_nama'
        },
        {
            name: 'sifat_kode'
        },
        {
            name: 'sifat_isaktif',
            type: 'int'
        },
        {
            name: 'sifat_properti'
        },
        {
            name: 'kelas_id'
        },
        {
            name: 'kelas_nama'
        },
        {
            name: 'kelas_kode'
        },
        {
            name: 'kelas_induk'
        },
        {
            name: 'kelas_isaktif',
            type: 'int'
        },
        {
            name: 'kelas_properti'
        },
        {
            name: 'lokasi_id'
        },
        {
            name: 'lokasi_nama'
        },
        {
            name: 'lokasi_kode'
        },
        {
            name: 'lokasi_induk'
        },
        {
            name: 'lokasi_isaktif',
            type: 'int'
        },
        {
            name: 'lokasi_properti'
        },
        {
            name: 'itipe_id'
        },
        {
            name: 'itipe_nama'
        },
        {
            name: 'itipe_kode'
        },
        {
            name: 'itipe_isaktif',
            type: 'int'
        },
        {
            name: 'itipe_properti'
        },
        {
            name: 'retensi_id'
        },
        {
            name: 'retensi_nama'
        },
        {
            name: 'retensi_hari'
        },
        {
            name: 'retensi_isaktif',
            type: 'int'
        },
        {
            name: 'retensi_properti'
        },
        {
            name: 'korespondensi_id'
        },
        {
            name: 'korespondensi_nomor'
        },
        {
            name: 'korespondensi_perihal'
        },
        {
            name: 'korespondensi_pengirim'
        },
        {
            name: 'korespondensi_penerima'
        },
        {
            name: 'korespondensi_isinternal'
        },
        {
            name: 'korespondensi_properti'
        },
        {
            name: 'iscabut',
            type: 'int'
        },
        {
            name: 'disposisi_prioritas_tgl',
            type: 'date'
        },
        {
            name: 'disposisi_useprioritas'
        },
        {
            name: 'isarahan',
            type: 'int'
        },
        {
            name: 'surat_kepada'
        },
        {
            name: 'disposisi_model_sub',
            type: 'int'
        },
        {
            name: 'sifat_color'
        },
        {
            name: 'unit_source_id'
        },
        {
            name: 'unit_source_kode'
        },
        {
            name: 'unit_source_nama'
        },
        {
            name: 'surat_nomor_isbatal'
        },
        {
            name: 'surat_ismusnah'
        },
        {
            name: 'surat_distribusi_iscabut'
        },
        {
            name: 'disposisi_rahasia_asisten',
            type: 'int'
        },
        {
            name: 'disposisi_rahasia_pgs',
            type: 'int'
        },
        {
            name: 'surat_useberkas',
            type: 'boolean'
        },
        {
            name: 'disposisi_profil_isganti',
            type: 'int'
        }
    ],

    hasOne: [
        {
            model: 'SIPAS.model.Sipas.Surat',
            primaryKey: 'surat_id',
            foreignKey: 'disposisi_surat',
            getterName: 'getSurat',
            setterName: 'SetSurat'
        },
        {
            model: 'SIPAS.model.Sipas.disposisi.Masuk',
            primaryKey: 'disposisi_masuk_id',
            foreignKey: 'disposisi_induk',
            getterName: 'getInduk',
            setterName: 'SetInduk'
        },
        {
            model: 'SIPAS.model.Sipas.Staf',
            primaryKey: 'staf_id',
            foreignKey: 'disposisi_staf',
            getterName: 'getPengirim',
            setterName: 'setPengirim'
        }
    ],

    hasMany: {
        model: 'SIPAS.model.Sipas.disposisi.Masuk',
        primaryKey: 'disposisi_id',
        foreignKey: 'disposisi_masuk_disposisi',
        name: 'fetchPenerima'
    },

    cabut: function(config) {
        config = Ext.apply({
            pencabut: config.pencabut,
            iscabut: config.iscabut,
            callback: Ext.emptyFn,
            success: Ext.emptyFn,
            failure: Ext.emptyFn,
            scope: this
        }, config);

        this.set({
            'disposisi_cabut_tgl': new Date(),
            'disposisi_cabut_staf' : config.pencabut,
            'iscabut' : config.iscabut
        });
        this.save(config);
    }

});