/*
 * File: app/model/Sipas/Klise.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.Klise', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    idProperty: 'klise_id',

    proxy: {
        type: 'ajax',
        api: {
            create: 'server.php/sipas/klise/create',
            read: 'server.php/sipas/klise/read',
            update: 'server.php/sipas/klise/update',
            destroy: 'server.php/sipas/klise/destroy'
        },
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    fields: [
        {
            name: 'klise_id'
        },
        {
            name: 'klise_nama'
        },
        {
            name: 'klise_kelompok'
        },
        {
            name: 'klise_isi'
        },
        {
            name: 'klise_ispetikan'
        },
        {
            defaultValue: 1,
            name: 'klise_isaktif',
            type: 'boolean'
        },
        {
            name: 'klise_properti'
        }
    ]
});