/*
 * File: app/store/Sipas/pelaporan/List.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.store.Sipas.pelaporan.List', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json',
        'Ext.data.Field',
        'Ext.util.Grouper'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Sipas.pelaporan.List',
            groupField: 'grup',
            proxy: {
                type: 'memory',
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'title'
                },
                {
                    name: 'bootstrap'
                },
                {
                    name: 'roleable'
                },
                {
                    name: 'roleName'
                },
                {
                    name: 'iconCls'
                },
                {
                    name: 'icon'
                },
                {
                    name: 'grup'
                },
                {
                    name: 'subtitle'
                },
                {
                    name: 'description'
                }
            ],
            groupers: {
                property: 'grup'
            }
        }, cfg)]);
    }
});