<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Sipas_model_Arsip_bagi_view extends Sipas_model_Arsip_bagi {
      
      public function __construct(){
        parent::__construct();
        $this->set_table_name('v_arsip_bagi');
        $this->set_primary('arsip_bagi_id');
        $this->set_fields(array(
            array('name'=>'arsip_bagi_id'),
            array('name'=>'arsip_bagi_arsip'),
            array('name'=>'arsip_bagi_unit'),
            array('name'=>'arsip_bagi_bolehtambah'),
            array('name'=>'arsip_bagi_bolehubah'),
            array('name'=>'arsip_bagi_bolehhapus'),
            array('name'=>'arsip_id'),
            array('name'=>'arsip_induk'),
            array('name'=>'arsip_nama'),
            array('name'=>'arsip_unit'),
            array('name'=>'arsip_isumum'),
            array('name'=>'arsip_isbagi'),
            array('name'=>'arsip_properti'),
            array('name'=>'arsip_induk_id'),
            array('name'=>'arsip_induk_nama'),
            array('name'=>'arsip_jumlah_dokumen'),
            // array('name'=>'properti_id'),
            // array('name'=>'properti_buat_tgl'),
            // array('name'=>'properti_buat_staf'),
            // array('name'=>'properti_buat_data')
            // array('name'=>'properti_ubah_tgl'),
            // array('name'=>'properti_ubah_staf'),
            // array('name'=>'properti_ubah_data'),
            // array('name'=>'properti_hapus_tgl'),
            // array('name'=>'properti_hapus_staf'),
            // array('name'=>'properti_hapus_data'),
            // array('name'=>'properti_pulih_tgl'),
            // array('name'=>'properti_pulih_staf'),
            // array('name'=>'properti_pulih_data'),
            // array('name'=>'properti_data'),
            // array('name'=>'properti_entitas'),
            // array('name'=>'properti_entitas_id'),
            // array('name'=>'properti_slug'),
            // array('name'=>'properti_isubah'),
            // array('name'=>'properti_ishapus'),
            // array('name'=>'properti_ispulih'),
            array('name'=>'properti_pembuat_id'),
            array('name'=>'properti_pembuat_kode'),
            array('name'=>'properti_pembuat_nama'),
            array('name'=>'properti_pembuat_unit'),
            array('name'=>'properti_pembuat_unit_nama'),
            array('name'=>'properti_pembuat_jabatan'),
            array('name'=>'properti_pembuat_jabatan_nama'),
            // array('name'=>'properti_pengubah_id'),
            // array('name'=>'properti_pengubah_kode'),
            // array('name'=>'properti_pengubah_nama'),
            // array('name'=>'properti_pengubah_unit'),
            // array('name'=>'properti_pengubah_unit_nama'),
            // array('name'=>'properti_pengubah_jabatan'),
            // array('name'=>'properti_pengubah_jabatan_nama'),
            // array('name'=>'properti_penghapus_id'),
            // array('name'=>'properti_penghapus_kode'),
            // array('name'=>'properti_penghapus_nama'),
            // array('name'=>'properti_penghapus_unit'),
            // array('name'=>'properti_penghapus_unit_nama'),
            // array('name'=>'properti_penghapus_jabatan'),
            // array('name'=>'properti_penghapus_jabatan_nama'),
            // array('name'=>'properti_pemulih_id'),
            // array('name'=>'properti_pemulih_kode'),
            // array('name'=>'properti_pemulih_nama'),
            // array('name'=>'properti_pemulih_unit'),
            // array('name'=>'properti_pemulih_unit_nama'),
            // array('name'=>'properti_pemulih_jabatan'),
            // array('name'=>'properti_pemulih_jabatan_nama'),
            array('name'=>'unit_id'),
            array('name'=>'unit_kode'),
            array('name'=>'unit_nama'),
            array('name'=>'arsip_bagi_unit_id'),
            array('name'=>'arsip_bagi_unit_kode'),
            array('name'=>'arsip_bagi_unit_nama')
        ));
    }
}