<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed');

$CI = get_instance();
$CI->model('sipas/surat_penerimask', true);

class Sipas_model_Surat_penerimask_view extends Sipas_model_Surat_penerimask {

    function __construct(){
        parent::__construct();
        $this->set_table_name('v_surat_penerimask');
        $this->set_primary('surat_penerimask_id');
        $this->set_fields(array(
            array('name'=>'surat_penerimask_id',                    'display'=>'Id','update'=>false,'unique'=>true,'notnull'=>true),
            array('name'=>'surat_penerimask_staf',                  'display'=>'Id Staf'),
            array('name'=>'surat_penerimask_profil',                'display'=>'Profil Staf'),
            array('name'=>'surat_penerimask_pelaku',                'display'=>'Id Pelaku'),
            array('name'=>'surat_penerimask_pelaku_profil',         'display'=>'Profil Pelaku'),
            array('name'=>'surat_penerimask_surat',                 'display'=>'Surat'),
            array('name'=>'surat_penerimask_level',                 'display'=>'Level'),
            array('name'=>'surat_penerimask_terima_tgl',            'display'=>'Tanggal Terima'),
            array('name'=>'surat_penerimask_status',                'display'=>'Status'),
            array('name'=>'surat_penerimask_status_tgl',            'display'=>'Tanggal Status'),
            array('name'=>'surat_penerimask_baca_tgl',              'display'=>'Tanggal Baca'),
            array('name'=>'surat_penerimask_properti',              'display'=>'Properti'),
            array('name'=>'surat_penerimask_gollama',               'display'=>'Golongan Lama'),
            array('name'=>'surat_penerimask_golbaru',               'display'=>'Golongan Baru'),
            array('name'=>'surat_penerimask_sglama',                'display'=>'Skala Gaji Tahunan Lama'),
            array('name'=>'surat_penerimask_sgbaru',                'display'=>'Skala Gaji Tahunan Baru'),
            array('name'=>'surat_penerimask_gplama',                'display'=>'Gaji Pokok Lama'),
            array('name'=>'surat_penerimask_gpbaru',                'display'=>'Gaji Pokok Baru'),
            array('name'=>'surat_penerimask_tmt',                   'display'=>'Terhitung Mulai Tgl Lama'),
            array('name'=>'surat_penerimask_jabatan_lama',          'display'=>'Jabatan Lama'),
            array('name'=>'surat_penerimask_jabatan_baru',          'display'=>'Jabatan Baru'),
            array('name'=>'surat_penerimask_jenjang_jabatan_lama',  'display'=>'Jenjang Jabatan Lama'),
            array('name'=>'surat_penerimask_jenjang_jabatan_baru',  'display'=>'Jenjang Jabatan Baru'),
            array('name'=>'surat_penerimask_keterangan',            'display'=>'Keterangan'),
            
            array('name' => 'surat_id', 'update' => false),
            array('name' => 'surat_arsip', 'update' => false),
            array('name' => 'surat_model', 'update' => false),
            array('name' => 'surat_model_sub', 'update' => false),
            // // array('name' => 'surat_itipe', 'update' => false),
            // array('name' => 'surat_registrasi', 'update' => false),
            // array('name' => 'surat_nomor', 'update' => false),
            // array('name' => 'surat_agenda', 'update' => false),
            // array('name' => 'surat_agenda_sub', 'update' => false),
            // array('name' => 'surat_tanggal', 'update' => false),
            // array('name' => 'surat_perihal', 'update' => false),
            // array('name' => 'surat_pengirim', 'update' => false),
            // array('name' => 'surat_tujuan', 'update' => false),
            // array('name' => 'surat_kepada', 'update' => false),
            // array('name' => 'surat_lampiran', 'update' => false),
            // array('name' => 'surat_ringkasan', 'update' => false),
            // array('name' => 'surat_catatan', 'update' => false),
            // array('name' => 'surat_unit', 'update' => false),
            // array('name' => 'surat_setuju_isurut', 'update' => false),
            // array('name' => 'surat_setuju', 'update' => false),
            // array('name' => 'surat_setuju_staf', 'update' => false),
            // array('name' => 'surat_setuju_profil', 'update' => false),
            // array('name' => 'surat_setuju_tgl', 'update' => false),
            // array('name' => 'surat_petikan_setuju', 'update' => false),
            // array('name' => 'surat_distribusi_staf', 'update' => false),
            // array('name' => 'surat_distribusi_profil', 'update' => false),
            // array('name' => 'surat_distribusi_tgl', 'update' => false),
            // array('name' => 'surat_distribusi_otomatis', 'update' => false),
            // array('name' => 'surat_selesai_staf', 'update' => false),
            // array('name' => 'surat_selesai_profil', 'update' => false),
            // array('name' => 'surat_selesai_tgl', 'update' => false),
            // array('name' => 'surat_terima_staf', 'update' => false),
            // array('name' => 'surat_korespondensi', 'update' => false),
            // array('name' => 'surat_korespondensi_surat', 'update' => false),
            // array('name' => 'surat_useretensi', 'update' => false),
            // array('name' => 'surat_retensi_tgl', 'update' => false),
            // array('name' => 'surat_prioritas', 'update' => false),
            // array('name' => 'surat_kelas', 'update' => false),
            // array('name' => 'surat_lokasi', 'update' => false),
            // array('name' => 'surat_jenis', 'update' => false),
            // array('name' => 'surat_media', 'update' => false),
            // array('name' => 'surat_sifat', 'update' => false),
            // array('name' => 'surat_properti', 'update' => false),

            array('name' => 'staf_id', 'update' => false),
            array('name' => 'staf_kode', 'update' => false),
            array('name' => 'staf_kelamin', 'update' => false),
            array('name' => 'staf_nama', 'update' => false),
            array('name' => 'unit_id', 'update' => false),
            array('name' => 'unit_nama', 'update' => false),
            array('name' => 'unit_kode', 'update' => false),
            array('name' => 'unit_rubrik', 'update' => false),
            array('name' => 'jabatan_id', 'update' => false),
            array('name' => 'jabatan_nama', 'update' => false),
            array('name' => 'jabatan_kode', 'update' => false),
            array('name' => 'jabatan_isnomor', 'update' => false),
            array('name' => 'jabatan_ispenerima', 'update' => false),
            array('name' => 'pelaku_id', 'update' => false),
            array('name' => 'pelaku_kode', 'update' => false),
            array('name' => 'pelaku_nama', 'update' => false),
            array('name' => 'pelaku_unit_id', 'update' => false),
            array('name' => 'pelaku_unit_nama', 'update' => false),
            array('name' => 'pelaku_jabatan_id', 'update' => false),
            array('name' => 'pelaku_jabatan_nama', 'update' => false),
            array('name' => 'jabatan_lama_id', 'update' => false),
            array('name' => 'jabatan_lama_nama', 'update' => false),
            array('name' => 'jabatan_lama_kode', 'update' => false),
            array('name' => 'jabatan_lama_unit_id', 'update' => false),
            array('name' => 'jabatan_lama_unit_nama', 'update' => false),
            array('name' => 'jabatan_baru_id', 'update' => false),
            array('name' => 'jabatan_baru_nama', 'update' => false),
            array('name' => 'jabatan_baru_kode', 'update' => false),
            array('name' => 'jabatan_baru_unit_id', 'update' => false),
            array('name' => 'jabatan_baru_unit_nama', 'update' => false),
            array('name' => 'golongan_lama_id', 'update' => false),
            array('name' => 'golongan_lama_level', 'update' => false),
            array('name' => 'golongan_lama_sgt', 'update' => false),
            array('name' => 'golongan_lama_gaji_pokok', 'update' => false),
            array('name' => 'golongan_baru_id', 'update' => false),
            array('name' => 'golongan_baru_level', 'update' => false),
            array('name' => 'golongan_baru_sgt', 'update' => false),
            array('name' => 'golongan_baru_gaji_pokok', 'update' => false)
        ));
    }
}