/*
 * File: app/view/Sipas/surat/agenda/aktif/Popup.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.surat.agenda.aktif.Popup', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_surat_agenda_aktif_popup',

    requires: [
        'SIPAS.view.Sipas.com.button.Save',
        'Ext.form.Panel',
        'Ext.form.field.Date',
        'Ext.form.field.Display',
        'Ext.button.Button'
    ],

    languageable: true,
    languageMode: 'title',
    languageCode: 'surat_aktifasi',
    border: false,
    height: 170,
    width: 500,
    layout: 'fit',
    title: 'Aktifasi Ulang Surat',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    cls: 'sipas_disposisi_penerima_detail_form',
                    autoScroll: true,
                    bodyPadding: '8 16 8 16',
                    header: false,
                    title: 'My Form',
                    items: [
                        {
                            xtype: 'datefield',
                            anchor: '75%',
                            width: 200,
                            fieldLabel: 'Perpanjang masa aktif surat sampai:',
                            labelWidth: 200,
                            name: 'surat_retensi_tgl',
                            emptyText: 'Pilih tanggal',
                            format: 'd M Y',
                            minValue: 'new Date()',
                            submitFormat: 'Y-m-d'
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            value: '<span style="color:grey">Masa Aktif Surat akan diperpanjang sesuai tanggal yang dipilih.</span>'
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});