/*
 * File: app/view/Sipas/surat/libnomor/Prop.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.surat.libnomor.Prop', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_surat_libnomor_prop',

    requires: [
        'SIPAS.view.Sipas.com.button.Delete',
        'SIPAS.view.Sipas.com.button.Edit',
        'SIPAS.view.Sipas.com.button.Save',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    languageable: true,
    languageCode: 'surat_libnomor_prop',
    languageMode: 'title',
    featureCode: 'surat_libnomor',
    ruleCode: 'surat_libnomor',
    width: 520,
    layout: 'fit',
    title: 'Penomoran Surat',
    maximizable: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    bodyPadding: '8 16 8 16',
                    header: false,
                    title: 'Penomoran',
                    items: [
                        {
                            xtype: 'numberfield',
                            width: 485,
                            fieldLabel: 'No. Urut',
                            labelWidth: 110,
                            name: 'surat_libnomor_value',
                            value: {
                                value: 1
                            },
                            size: 10,
                            allowDecimals: false,
                            allowExponential: false,
                            minValue: 1
                        },
                        {
                            xtype: 'combobox',
                            itemId: 'comboModel',
                            width: 485,
                            fieldLabel: 'Model',
                            labelWidth: 110,
                            name: 'surat_libnomor_model',
                            displayField: 'display',
                            store: {
                                fields: [
                                    'display',
                                    'modelvalue'
                                ],
                                data: [
                                    {
                                        display: 'Tidak menggunakan model',
                                        modelvalue: null
                                    },
                                    {
                                        display: 'No. Registrasi',
                                        modelvalue: 0
                                    },
                                    {
                                        display: 'Eksternal',
                                        modelvalue: 2
                                    },
                                    {
                                        display: 'Internal',
                                        modelvalue: 4
                                    },
                                    {
                                        display: 'Notadinas',
                                        modelvalue: 6
                                    }
                                ]
                            },
                            valueField: 'modelvalue'
                        },
                        {
                            xtype: 'numberfield',
                            fieldLabel: 'Tahun',
                            labelWidth: 110,
                            name: 'surat_libnomor_tahun',
                            value: '(new Date()).getFullYear()',
                            enforceMaxLength: true,
                            maxLength: 4,
                            minLength: 4,
                            size: 5,
                            validateBlank: true,
                            allowDecimals: false,
                            allowExponential: false,
                            autoStripChars: true,
                            minValue: 1500,
                            listeners: {
                                afterrender: {
                                    fn: me.onNumberfieldAfterRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getJenis',
                            width: 485,
                            fieldLabel: 'Jenis',
                            labelWidth: 110,
                            name: 'surat_libnomor_jenis',
                            autoSelect: false,
                            displayField: 'jenis_display',
                            store: 'Sipas.jenis.Combo',
                            valueField: 'jenis_id'
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getKelas',
                            width: 450,
                            fieldLabel: 'Klasifikasi',
                            labelWidth: 110,
                            name: 'surat_libnomor_kelas',
                            autoSelect: false,
                            displayField: 'kelas_display',
                            store: 'Sipas.kelas.Combo',
                            valueField: 'kelas_id'
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getSifat',
                            width: 450,
                            fieldLabel: 'Sifat',
                            labelWidth: 110,
                            name: 'surat_libnomor_sifat',
                            autoSelect: false,
                            displayField: 'sifat_display',
                            store: 'Sipas.sifat.Combo',
                            valueField: 'sifat_id'
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getLokasi',
                            width: 450,
                            fieldLabel: 'Lokasi',
                            labelWidth: 110,
                            name: 'surat_libnomor_lokasi',
                            autoSelect: false,
                            displayField: 'lokasi_display',
                            store: 'Sipas.lokasi.Combo',
                            valueField: 'lokasi_id'
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getUnitPembuat',
                            languageable: true,
                            languageCode: 'unit_pembuat',
                            languageMode: 'text',
                            width: 485,
                            fieldLabel: 'Unit Pembuat',
                            labelWidth: 110,
                            name: 'surat_libnomor_unit_pembuat',
                            autoSelect: false,
                            displayField: 'unit_display',
                            store: 'Sipas.unit.Combo',
                            valueField: 'unit_id'
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getUnitPenyetuju',
                            languageable: true,
                            languageCode: 'unit_penyetuju',
                            languageMode: 'text',
                            width: 450,
                            fieldLabel: 'Unit Penyetuju',
                            labelWidth: 110,
                            name: 'surat_libnomor_unit_penyetuju',
                            autoSelect: false,
                            displayField: 'unit_display',
                            store: 'Sipas.surat.libnomor.unit.penyetuju.Combo',
                            valueField: 'unit_id'
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getJabatanPembuat',
                            width: 450,
                            fieldLabel: 'Jabatan Pembuat',
                            labelWidth: 110,
                            name: 'surat_libnomor_jabatan_pembuat',
                            autoSelect: false,
                            displayField: 'jabatan_nama',
                            store: 'Sipas.jabatan.Combo',
                            valueField: 'jabatan_id'
                        },
                        {
                            xtype: 'combobox',
                            associated: true,
                            assocRecord: 'getJabatanPenyetuju',
                            width: 450,
                            fieldLabel: 'Jabatan Penyetuju',
                            labelWidth: 110,
                            name: 'surat_libnomor_jabatan_penyetuju',
                            autoSelect: false,
                            displayField: 'jabatan_nama',
                            store: 'Sipas.surat.libnomor.jabatan.penyetuju.Combo',
                            valueField: 'jabatan_id'
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'container',
                            dock: 'bottom',
                            itemId: 'toolbarAction',
                            ui: 'footer',
                            layout: {
                                type: 'hbox',
                                defaultMargins: {
                                    top: 0,
                                    right: 4,
                                    bottom: 6,
                                    left: 4
                                },
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'sipas_com_button_delete'
                                },
                                {
                                    xtype: 'sipas_com_button_edit'
                                },
                                {
                                    xtype: 'sipas_com_button_save'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onNumberfieldAfterRender: function(component, eOpts) {
        var $this = this,
            $app = SIPAS.getApplication(),
            $runtime = $app.Runtime().getValue(),
            year = (new Date()).getFullYear();

            component.setMaxValue(year);
            if($runtime.useRentangTahunPenomoran){
                var rentang = $runtime.rentangTahunPenomoran - 1,
                    value = year - rentang;
                component.setMinValue(value);
            }

    }

});