/*
 * File: app/model/Sipas/surat/Ekspedisi.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.surat.Ekspedisi', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.association.HasOne',
        'Ext.data.Field'
    ],
    uses: [
        'SIPAS.model.Sipas.Disposisi',
        'SIPAS.model.Sipas.Surat',
        'SIPAS.model.Sipas.disposisi.Masuk'
    ],

    hasOne: [
        {
            associationKey: 'disposis_record',
            model: 'SIPAS.model.Sipas.Disposisi',
            primaryKey: 'disposisi_id',
            foreignKey: 'disposisi_id',
            getterName: 'getDisposisi',
            setterName: 'setDisposisi'
        },
        {
            associationKey: 'surat_record',
            model: 'SIPAS.model.Sipas.Surat',
            primaryKey: 'surat_id',
            foreignKey: 'disposisi_surat',
            getterName: 'getSurat',
            setterName: 'setSurat'
        },
        {
            associationKey: 'disposisi_masuk_record',
            model: 'SIPAS.model.Sipas.disposisi.Masuk',
            primaryKey: 'disposisi_masuk_id',
            foreignKey: 'disposisi_masuk_id',
            getterName: 'getDisposisiPenerima',
            setterName: 'setDisposisiPeneirima'
        }
    ],

    fields: [
        {
            name: 'disposisi',
            type: 'boolean'
        },
        {
            name: 'disposisi_id'
        },
        {
            name: 'disposisi_record'
        },
        {
            name: 'disposisi_masuk',
            type: 'boolean'
        },
        {
            name: 'disposisi_masuk_id'
        },
        {
            name: 'disposisi_masuk_record'
        },
        {
            name: 'disposisi_masuk_aksi'
        },
        {
            name: 'disposisi_masuk_staf'
        },
        {
            name: 'disposisi_masuk_profil'
        },
        {
            name: 'disposisi_masuk_disposisi'
        },
        {
            name: 'disposisi_masuk_status'
        },
        {
            name: 'disposisi_masuk_keterangan'
        },
        {
            name: 'disposisi_masuk_pesan'
        },
        {
            name: 'disposisi_nomor'
        },
        {
            name: 'disposisi_staf'
        },
        {
            name: 'disposisi_profil'
        },
        {
            name: 'disposisi_pengirim_nama'
        },
        {
            name: 'disposisi_tgl'
        },
        {
            name: 'disposisi_surat'
        },
        {
            name: 'disposisi_pesan'
        },
        {
            name: 'disposisi_induk'
        },
        {
            name: 'surat_properti_buat_nama'
        },
        {
            name: 'surat_properti_buat_tgl'
        },
        {
            name: 'surat',
            type: 'boolean'
        },
        {
            name: 'surat_id'
        },
        {
            name: 'surat_record'
        },
        {
            name: 'surat_agenda'
        },
        {
            name: 'surat_nomor'
        },
        {
            name: 'surat_perihal'
        },
        {
            name: 'surat_pengirim'
        },
        {
            name: 'surat_tanggal'
        },
        {
            name: 'surat_setuju'
        },
        {
            name: 'perintah_nama'
        },
        {
            name: 'aksi_nama'
        },
        {
            name: 'disposisi_masuk_penerima_id'
        },
        {
            name: 'disposisi_masuk_penerima_nama'
        },
        {
            name: 'disposisi_masuk_penerima_unit_nama'
        },
        {
            name: 'disposisi_masuk_penerima_jabatan_nama'
        },
        {
            name: 'disposisi_pengirim_id'
        },
        {
            name: 'disposisi_pengirim_unit_nama'
        },
        {
            name: 'disposisi_pengirim_jabatan_nama'
        }
    ],

    isDisposisi: function() {
        return this.get('disposisi');
    },

    isDisposisiMasuk: function() {
        return this.get('disposisi_masuk');
    },

    genStatus: function(record) {

        if(record.isRoot()) return "";

        if(record.isDisposisiPenerima()){
        	var recdata = record.get('disposisi_masuk_record'),
        		valdata = recdata && parseInt(recdata.disposisi_masuk_status);
        }

        return "";
    }

});