/*
 * File: app/view/Sipas/session/profile/viewer/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.session.profile.viewer.Pane', {
    extend: 'Ext.form.Panel',
    alias: 'widget.sipas_session_profile_viewer_pane',

    requires: [
        'SIPAS.view.Sipas.com.button.Valuable',
        'Ext.container.Container',
        'Ext.button.Button'
    ],

    border: false,
    cls: 'sipas_session_profile_viewer_pane x-panel-transparentbody x-panel-transparentheader',
    itemId: 'formProfile',
    frameHeader: false,
    title: 'Profil',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'container',
                    flex: 1,
                    cls: 'containerProfile',
                    itemId: 'containerProfile',
                    layout: {
                        type: 'vbox',
                        pack: 'end',
                        padding: '0 16'
                    },
                    items: [
                        {
                            xtype: 'container',
                            cls: 'profilePic',
                            height: 56,
                            hidden: true,
                            itemId: 'containerImage',
                            style: {
                                'text-align': 'center'
                            },
                            width: 56,
                            layout: 'fit'
                        }
                    ]
                },
                {
                    xtype: 'sipas_com_button_valuable',
                    associated: true,
                    bootstrap: 'Sipas.session.profile.editor.Pane',
                    popupLauncher: true,
                    featureable: true,
                    featureName: 'profil',
                    valueTemplate: '<div class="titletext">{staf_nama}</div> <div class="subtext">{unit_nama}</div>',
                    cls: 'x-btn-profile',
                    itemId: 'buttonProfile',
                    iconAlign: 'top',
                    scale: 'large',
                    text: 'Profile',
                    textAlign: 'left'
                }
            ]
        });

        me.callParent(arguments);
    }

});