/*
 * File: app/view/Sipas/dashboard/board/atribut/topmost/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.dashboard.board.atribut.topmost.Pane', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.sipas_dashboard_board_atribut_topmost_pane',

    requires: [
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Date',
        'Ext.grid.View'
    ],

    title: 'Atribut Paling Sering Digunakan',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            columns: [
                {
                    xtype: 'rownumberer'
                },
                {
                    xtype: 'gridcolumn',
                    sortable: true,
                    dataIndex: 'string',
                    text: 'Atribut',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    sortable: true,
                    dataIndex: 'string',
                    text: 'Nama Atribut',
                    flex: 1
                },
                {
                    xtype: 'datecolumn',
                    sortable: true,
                    align: 'center',
                    dataIndex: 'date',
                    text: 'Terakhir Digunakan',
                    flex: 1,
                    format: 'd-m-Y'
                }
            ]
        });

        me.callParent(arguments);
    }

});