/*
 * File: app/view/Sipas/surat/agenda/nomor/salin/Lookup.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.surat.agenda.nomor.salin.Lookup', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_surat_agenda_nomor_salin_lookup',

    requires: [
        'SIPAS.view.Sipas.com.button.Putin',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.grid.column.Date',
        'Ext.selection.CheckboxModel',
        'Ext.toolbar.Paging',
        'Ext.button.Button'
    ],

    languageable: true,
    languageCode: 'list_salin_nomor',
    languageMode: 'title',
    height: 400,
    minHeight: 100,
    minWidth: 200,
    width: 700,
    layout: 'fit',
    title: 'Daftar List Salin Nomor',
    maximizable: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                me.processListSalinNomor({
                    xtype: 'gridpanel',
                    border: false,
                    allowDeselect: true,
                    emptyText: 'Tidak Ada Data',
                    store: 'Sipas.surat.salin.Lookup',
                    viewConfig: {
                        deferEmptyText: false,
                        emptyText: 'Tidak Ada Data'
                    },
                    columns: [
                        {
                            xtype: 'datecolumn',
                            width: 100,
                            sortable: true,
                            dataIndex: 'surat_tanggal',
                            text: 'Tgl.Surat',
                            format: 'd M Y'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value){
                                    return '<span class="blue-700-i">'+value+'</span>';
                                } else {
                                    return '<span class="alternative">-</span>';
                                }
                            },
                            filterable: true,
                            items: {
                                xtype: 'textfield',
                                emptyText: 'Cari No Surat',
                                flex: 1,
                                margin: 2,
                                listeners: {
                                    change: function(textfield, e, eOpts){
                                this.up('gridpanel').filterHeader(this);
                                }
                                }
                            },
                            width: 140,
                            sortable: true,
                            dataIndex: 'surat_nomor',
                            text: 'No.Surat'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value){
                                    return value;
                                } else {
                                    return '<span class="alternative">-</span>';
                                }
                            },
                            filterable: true,
                            items: {
                                xtype: 'textfield',
                                emptyText: 'Cari No Registrasi',
                                flex: 1,
                                margin: 2,
                                listeners: {
                                    change: function(textfield, e, eOpts){
                                this.up('gridpanel').filterHeader(this);
                                }
                                }
                            },
                            width: 140,
                            sortable: true,
                            dataIndex: 'surat_registrasi',
                            text: 'No.Registrasi'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (value){
                                    return value;
                                } else {
                                    return '<span class="alternative">-</span>';
                                }
                            },
                            filterable: true,
                            items: {
                                xtype: 'textfield',
                                emptyText: 'Cari Perihal Surat',
                                flex: 1,
                                margin: 2,
                                listeners: {
                                    change: function(textfield, e, eOpts){
                                this.up('gridpanel').filterHeader(this);
                                }
                                }
                            },
                            width: 291,
                            sortable: true,
                            dataIndex: 'surat_perihal',
                            text: 'Perihal'
                        }
                    ],
                    selModel: Ext.create('Ext.selection.CheckboxModel', {
                        mode: 'SINGLE',
                        showHeaderCheckbox: false
                    }),
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'Sipas.surat.salin.Lookup'
                        }
                    ]
                })
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    itemId: 'toolbarControl',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_putin',
                            disabled: true
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processListSalinNomor: function(config) {
        var filters = {
            ftype: 'filters',
            encode: true,
            local: false
        };

        if (! config.features) {
            config.features=filters;
        } else {
            config.features.push(filters);
        }

        return config;
    }

});