/*
 * File: app/view/Sipas/prioritas/Prop.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.prioritas.Prop', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_prioritas_prop',

    requires: [
        'SIPAS.view.Sipas.com.button.Delete',
        'SIPAS.view.Sipas.com.button.Edit',
        'SIPAS.view.Sipas.com.button.Save',
        'Ext.form.Panel',
        'Ext.form.field.Number',
        'Ext.XTemplate',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.form.FieldSet',
        'Ext.form.field.Checkbox',
        'Ext.button.Button'
    ],

    languageable: true,
    languageMode: 'title',
    languageCode: 'prioritas_prop',
    minWidth: 460,
    width: 460,
    constrain: true,
    layout: 'fit',
    constrainHeader: true,
    title: 'Urgensi Surat',
    maximizable: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    bodyPadding: '8 16 8 16',
                    header: false,
                    title: 'Prioritas Surat',
                    items: [
                        {
                            xtype: 'textfield',
                            languageable: true,
                            languageMode: 'fieldLabel',
                            languageCode: 'nama_prioritas_prop',
                            anchor: '100%',
                            fieldLabel: 'Nama Urgensi',
                            labelWidth: 135,
                            name: 'prioritas_nama',
                            emptyText: 'Masukkan nama prioritas'
                        },
                        {
                            xtype: 'textfield',
                            languageable: true,
                            languageMode: 'fieldLabel',
                            languageCode: 'kode_prioritas_prop',
                            width: 240,
                            fieldLabel: 'Kode Urgensi',
                            labelWidth: 135,
                            name: 'prioritas_kode',
                            emptyText: 'Masukkan kode'
                        },
                        {
                            xtype: 'container',
                            itemId: 'containerPrioritas',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'numberfield',
                                    featureName: 'prioritas_waktu',
                                    featureable: true,
                                    languageable: true,
                                    languageMode: 'fieldLabel',
                                    languageCode: 'lama_prioritas_prop',
                                    width: 180,
                                    afterSubTpl: [
                                        'hari'
                                    ],
                                    fieldLabel: 'Lama Urgensi',
                                    labelWidth: 135,
                                    name: 'prioritas_retensi',
                                    emptyText: '0',
                                    hideTrigger: true,
                                    allowDecimals: false,
                                    allowExponential: false
                                },
                                {
                                    xtype: 'combobox',
                                    cls: 'x-field-triggeronly',
                                    itemId: 'comboRetensi',
                                    width: 20,
                                    formItemCls: 'comboRetensi',
                                    submitValue: false,
                                    emptyText: 'Pilih masa aktif',
                                    editable: false,
                                    matchFieldWidth: false,
                                    anyMatch: true,
                                    displayField: 'retensi_nama',
                                    forceSelection: true,
                                    pageSize: 15,
                                    store: 'Sipas.retensi.Combo',
                                    valueField: 'retensi_hari',
                                    listeners: {
                                        afterrender: {
                                            fn: me.onRetensiAfterRender,
                                            scope: me
                                        },
                                        select: {
                                            fn: me.onRetensiSelect,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            hidden: true,
                            fieldLabel: 'Keterangan',
                            labelAlign: 'top',
                            name: 'prioritas_keterangan',
                            rows: 3
                        },
                        {
                            xtype: 'fieldset',
                            padding: 0,
                            title: 'Status Aktif',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    labelWidth: 135,
                                    name: 'prioritas_isaktif',
                                    boxLabel: 'Aktif',
                                    inputValue: '1'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    itemId: 'toolbarAction',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_delete',
                            roleable: true,
                            roleName: 'prioritas_delete'
                        },
                        {
                            xtype: 'sipas_com_button_edit',
                            roleable: true,
                            roleName: 'prioritas_update'
                        },
                        {
                            xtype: 'sipas_com_button_save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onRetensiAfterRender: function(component, eOpts) {
        var c = component.up('#containerPrioritas').down('[name=prioritas_retensi]') || {};
        if(c.readOnly) {
            component.hide();
        }else{
            component.getStore().reload();
            component.setValue(0);

        }
    },

    onRetensiSelect: function(combo, records, eOpts) {
        numberfield = combo.up('#containerPrioritas').down('[name=prioritas_retensi]');

        if(!numberfield.readOnly){
            numberfield.setValue(combo.getValue());
        }
    }

});