/*
 * File: app/model/Sipas/disposisi/perintah/Log.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.disposisi.perintah.Log', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field',
        'Ext.data.association.HasOne'
    ],
    uses: [
        'SIPAS.model.Sipas.Perintah'
    ],

    idProperty: 'disposisi_perintah_log_id',

    proxy: {
        type: 'ajax',
        api: {
            create: 'server.php/sipas/disposisi_perintah_log/create',
            read: 'server.php/sipas/disposisi_perintah_log/read'
        },
        reader: {
            type: 'json',
            messageProperty: 'message',
            root: 'data'
        }
    },

    fields: [
        {
            name: 'disposisi_perintah_log_id'
        },
        {
            name: 'disposisi_perintah_log_disposisi'
        },
        {
            name: 'disposisi_perintah_log_perintah'
        },
        {
            name: 'disposisi_perintah_log_pesan'
        },
        {
            name: 'disposisi_perintah_log_staf'
        },
        {
            name: 'disposisi_perintah_log_tgl',
            type: 'date'
        },
        {
            name: 'perintah_id'
        },
        {
            name: 'perintah_kode'
        },
        {
            name: 'perintah_nama'
        },
        {
            name: 'staf_id'
        },
        {
            name: 'staf_nama'
        },
        {
            name: 'staf_isaktif'
        },
        {
            name: 'unit_nama'
        },
        {
            name: 'jabatan_nama'
        }
    ],

    hasOne: {
        model: 'SIPAS.model.Sipas.Perintah',
        primaryKey: 'perintah_id',
        foreignKey: 'disposisi_perintah_log_perintah',
        getterName: 'getPerintah',
        setterName: 'setPerintah'
    }
});