/*
 * File: app/store/Sipas/bank/Combo.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.store.Sipas.bank.Combo', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: false,
            storeId: 'Sipas.bank.Combo',
            data: [
                {
                    tipe_id: '0',
                    tipe_nama: '-- Semua Surat --'
                },
                {
                    tipe_id: '1',
                    tipe_nama: 'Surat Masuk Eksternal'
                },
                {
                    tipe_id: '2',
                    tipe_nama: 'Surat Keluar Eksternal'
                },
                {
                    tipe_id: '3',
                    tipe_nama: 'Surat Masuk Internal'
                },
                {
                    tipe_id: '4',
                    tipe_nama: 'Surat Keluar Internal'
                },
                {
                    tipe_id: '6',
                    tipe_nama: 'Surat Keputusan Internal'
                }
            ],
            fields: [
                {
                    name: 'tipe_id'
                },
                {
                    name: 'tipe_nama'
                }
            ]
        }, cfg)]);
    }
});