/*
 * File: app/view/Sipas/surat/ekspedisi/batal/Popup.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.surat.ekspedisi.batal.Popup', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_surat_ekspedisi_batal_popup',

    requires: [
        'SIPAS.view.Sipas.com.button.Save',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    languageable: true,
    languageCode: 'batal_komentar_prop',
    languageMode: 'title',
    minHeight: 100,
    minWidth: 500,
    width: 500,
    layout: 'fit',
    title: 'Komentar',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    itemId: 'form',
                    autoScroll: true,
                    bodyPadding: '8 8',
                    frameHeader: false,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            margins: '0 7 0 7',
                            layout: 'anchor',
                            labelWidth: 80,
                            items: [
                                {
                                    xtype: 'textareafield',
                                    anchor: '100%',
                                    itemId: 'textPesan',
                                    fieldLabel: 'Uraian Pesan',
                                    hideLabel: true,
                                    labelWidth: 140,
                                    name: 'surat_distribusi_cabut_pesan',
                                    emptyText: 'Uraian'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    margin: '0 15 8 0',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_save',
                            action: 'dosave',
                            languageable: true,
                            languageMode: 'text',
                            languageCode: 'batalkan_button',
                            cls: 'x-btn-fill x-btn-bordered x-btn-danger',
                            itemId: 'btnBatalDis',
                            text: 'Batalkan'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});