/*
 * File: app/view/Sipas/internal/masuk/agenda/distribusi/Prop.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.internal.masuk.agenda.distribusi.Prop', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_internal_masuk_agenda_distribusi_prop',

    requires: [
        'SIPAS.view.Sipas.com.surat.Pane',
        'SIPAS.view.Sipas.disposisi.forward.penerima.List',
        'SIPAS.view.Sipas.internal.masuk.agenda.distribusi.penerima.List',
        'SIPAS.view.Sipas.internal.masuk.agenda.distribusi.jabatan.List',
        'SIPAS.view.Sipas.com.button.Disposisi',
        'Ext.form.Panel',
        'Ext.form.FieldSet',
        'Ext.grid.Panel',
        'Ext.tab.Panel',
        'Ext.tab.Tab'
    ],

    height: 615,
    width: 500,
    layout: 'fit',
    title: 'Distribusi',
    maximizable: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    withSurat: true,
                    withSender: true,
                    border: false,
                    width: 490,
                    autoScroll: true,
                    collapsed: false,
                    header: false,
                    manageHeight: false,
                    title: 'Form Meneruskan Internal',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'sipas_com_surat_pane',
                            associated: true,
                            border: false,
                            itemId: 'infoSurat',
                            margin: '0 7 0 16',
                            maxHeight: 135,
                            autoScroll: true,
                            flex: 1
                        },
                        {
                            xtype: 'sipas_disposisi_forward_penerima_list',
                            associated: true,
                            border: false,
                            flex: 1
                        },
                        {
                            xtype: 'tabpanel',
                            flex: 1,
                            hidden: true,
                            activeTab: 0,
                            items: [
                                {
                                    xtype: 'panel',
                                    itemId: 'panelPenerima',
                                    title: 'Penerima ',
                                    tabConfig: {
                                        xtype: 'tab',
                                        itemId: 'tabStaf'
                                    },
                                    items: [
                                        {
                                            xtype: 'sipas_internal_masuk_agenda_distribusi_penerima_list',
                                            associated: true,
                                            border: false,
                                            height: 500,
                                            itemId: 'listPenerima',
                                            minHeight: 360
                                        }
                                    ]
                                },
                                {
                                    xtype: 'panel',
                                    itemId: 'panelTembusan',
                                    title: 'Tembusan',
                                    tabConfig: {
                                        xtype: 'tab',
                                        itemId: 'tabTembusan'
                                    },
                                    items: [
                                        {
                                            xtype: 'sipas_internal_masuk_agenda_distribusi_jabatan_list',
                                            associated: true,
                                            border: false,
                                            height: 500,
                                            itemId: 'listTembusan',
                                            minHeight: 360
                                        }
                                    ]
                                }
                            ]
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'container',
                            flex: 1,
                            dock: 'bottom',
                            itemId: 'toolbarAction',
                            ui: 'footer',
                            layout: {
                                type: 'hbox',
                                defaultMargins: {
                                    top: 4,
                                    right: 4,
                                    bottom: 6,
                                    left: 4
                                },
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'sipas_com_button_disposisi',
                                    action: 'dosave',
                                    itemId: 'btnKirim',
                                    text: '<strong>KIRIM</strong>'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});