/*
 * File: app/view/Sipas/peran/List.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.peran.List', {
    extend: 'Ext.grid.Panel',
    alias: 'widget.sipas_peran_list',

    requires: [
        'SIPAS.view.Sipas.com.button.Refresh',
        'SIPAS.view.Sipas.com.button.Add',
        'SIPAS.view.Sipas.com.button.View',
        'SIPAS.view.Sipas.com.button.ToggleFilter',
        'Ext.button.Button',
        'Ext.toolbar.Fill',
        'Ext.form.field.ComboBox',
        'Ext.grid.RowNumberer',
        'Ext.grid.View',
        'Ext.toolbar.Paging',
        'Ext.ux.grid.FiltersFeature'
    ],

    roleName: 'hakakses',
    clickToView: true,
    border: 0,
    itemId: 'listSipasPeran',
    header: false,
    title: 'Daftar Hak Akses',
    emptyText: 'Tidak ada Data',
    store: 'Sipas.peran.aktif.List',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        }
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_refresh'
                        },
                        {
                            xtype: 'sipas_com_button_add',
                            roleName: 'hakakses_insert',
                            roleable: true
                        },
                        {
                            xtype: 'sipas_com_button_view',
                            disabled: true,
                            hidden: true
                        },
                        {
                            xtype: 'sipas_com_button_togglefilter',
                            toggleHandler: function(button, state) {
                                button.up('grid').query('gridcolumn textfield').forEach(function(field){
                                    state ? field.show():field.hide();
                                });
                            }
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'combobox',
                            itemId: 'Aktif',
                            labelAlign: 'right',
                            value: 'Aktif',
                            editable: false,
                            hideTrigger: true,
                            displayField: 'nama',
                            store: {
                                fields: [
                                    'value',
                                    'nama'
                                ],
                                data: [
                                    {
                                        value: 0,
                                        nama: 'Semua'
                                    },
                                    {
                                        value: 1,
                                        nama: 'Aktif'
                                    },
                                    {
                                        value: 2,
                                        nama: 'Tidak Aktif'
                                    }
                                ]
                            },
                            valueField: 'value'
                        }
                    ]
                },
                {
                    xtype: 'pagingtoolbar',
                    dock: 'bottom',
                    hidden: true,
                    width: 360,
                    displayInfo: true,
                    store: 'Sipas.peran.aktif.List'
                }
            ],
            columns: [
                {
                    xtype: 'rownumberer',
                    width: 40
                },
                {
                    xtype: 'gridcolumn',
                    items: {
                        xtype: 'textfield',
                        emptyText: 'Cari Nama Hak Akses',
                        flex: 1,
                        margin: 2,
                        listeners: {
                            change: function(textfield, e, eOpts){
                                                            this.up('gridpanel').filterHeader(this);
                                                        }
                        }
                    },
                    filterable: true,
                    minWidth: 160,
                    sortable: true,
                    dataIndex: 'peran_nama',
                    text: 'Nama Hak Akses',
                    flex: 1
                },
                {
                    xtype: 'gridcolumn',
                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                        if(value){
                            return '<i class="icon ion-md-person"></i> '+ value;
                        }
                    },
                    width: 60,
                    dataIndex: 'peran_staf_jumlah',
                    text: '<i class="iicon on-md-person"></i>'
                }
            ]
        });

        me.processSipasperanList(me);
        me.callParent(arguments);
    },

    processSipasperanList: function(config) {
        var filters = {
                    ftype: 'filters',
                    encode: true,
                    local: false
                };

                if (! config.features) {
                    config.features=filters;
                } else {
                    config.features.push(filters);
                }

                return config;
    }

});