/*
 * File: app/view/Sipas/riwayat/session/perintah/Popup.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.riwayat.session.perintah.Popup', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_riwayat_session_perintah_popup',

    requires: [
        'SIPAS.view.Sipas.com.button.Save',
        'Ext.form.Panel',
        'Ext.form.FieldContainer',
        'Ext.form.field.ComboBox',
        'Ext.form.field.TextArea',
        'Ext.button.Button'
    ],

    languageable: true,
    languageCode: 'perintah_prop',
    languageMode: 'title',
    minHeight: 250,
    minWidth: 500,
    width: 500,
    layout: 'fit',
    title: 'Arahan',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    itemId: 'form',
                    autoScroll: true,
                    bodyPadding: '8 8 8 8',
                    frameHeader: false,
                    header: false,
                    title: 'My Form',
                    layout: {
                        type: 'vbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'fieldcontainer',
                            height: 120,
                            itemId: 'panePerintah',
                            margin: '0 7 0 7',
                            layout: 'anchor',
                            items: [
                                {
                                    xtype: 'combobox',
                                    languageCode: 'perintah_combo',
                                    languageMode: 'fieldLabel',
                                    languageable: true,
                                    associated: true,
                                    anchor: '100%',
                                    itemId: 'comPerintah',
                                    width: 360,
                                    fieldLabel: 'Perintah',
                                    labelAlign: 'top',
                                    name: 'disposisi_perintah_log_perintah',
                                    emptyText: 'Silahkan Pilih Arahan',
                                    displayField: 'perintah_nama',
                                    forceSelection: true,
                                    queryMode: 'local',
                                    store: 'Sipas.perintah.Combo',
                                    valueField: 'perintah_id'
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    layout: 'anchor',
                                    labelWidth: 140,
                                    items: [
                                        {
                                            xtype: 'textareafield',
                                            anchor: '100%',
                                            itemId: 'textPerintah',
                                            fieldLabel: 'Uraian Tindakan',
                                            hideLabel: true,
                                            labelWidth: 140,
                                            name: 'disposisi_perintah_log_pesan',
                                            emptyText: 'Uraian'
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_save',
                            action: 'dosave',
                            languageable: true,
                            languageMode: 'text',
                            languageCode: 'perintah_button',
                            cls: 'x-btn-fill x-btn-bordered x-btn-info',
                            itemId: 'btnPerintah',
                            text: 'Perbarui Tindakan'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});