/*
 * File: app/view/Sipas/jabatan/Prop.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.jabatan.Prop', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_jabatan_prop',

    requires: [
        'SIPAS.view.Sipas.com.button.Cross',
        'SIPAS.view.Sipas.com.button.Delete',
        'SIPAS.view.Sipas.com.button.Edit',
        'SIPAS.view.Sipas.com.button.Save',
        'Ext.form.Panel',
        'Ext.form.field.TextArea',
        'Ext.form.FieldContainer',
        'Ext.form.field.Hidden',
        'Ext.form.field.ComboBox',
        'Ext.button.Button',
        'Ext.form.FieldSet',
        'Ext.form.field.Checkbox'
    ],

    minHeight: 240,
    minWidth: 400,
    width: 520,
    constrain: true,
    layout: 'fit',
    constrainHeader: true,
    title: 'Jabatan',
    maximizable: true,
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    border: false,
                    bodyPadding: '8 16 8 16',
                    header: false,
                    title: 'Jabatan',
                    items: [
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            itemId: 'jabatan_nama',
                            fieldLabel: 'Nama Jabatan',
                            name: 'jabatan_nama',
                            emptyText: 'Masukkan nama jabatan'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'jabatan_kode',
                            width: 260,
                            fieldLabel: 'Kode Jabatan',
                            name: 'jabatan_kode',
                            emptyText: 'Masukkan kode jabatan'
                        },
                        {
                            xtype: 'textfield',
                            itemId: 'jabatan_pos_code',
                            width: 260,
                            fieldLabel: 'Pos Code',
                            name: 'jabatan_pos_code',
                            emptyText: 'Masukkan pos code'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            hidden: true,
                            itemId: 'jabatan_keterangan',
                            width: 368,
                            fieldLabel: 'Keterangan',
                            name: 'jabatan_keterangan'
                        },
                        {
                            xtype: 'fieldcontainer',
                            anchor: '100%',
                            itemId: 'containerParent',
                            fieldLabel: 'Anak dari',
                            layout: {
                                type: 'hbox',
                                align: 'stretch'
                            },
                            items: [
                                {
                                    xtype: 'hiddenfield',
                                    flex: 1,
                                    itemId: 'hiddenParent',
                                    fieldLabel: 'Label',
                                    name: 'jabatan_induk1'
                                },
                                {
                                    xtype: 'triggerfield',
                                    flex: 1,
                                    hidden: true,
                                    itemId: 'comboParent',
                                    fieldLabel: '',
                                    name: 'jabatan_induk_nama',
                                    submitValue: false,
                                    editable: false
                                },
                                {
                                    xtype: 'combobox',
                                    bootstrapProperty: 'Sipas.unit.Prop',
                                    associated: true,
                                    flex: 1,
                                    itemId: 'comboInduk',
                                    name: 'jabatan_induk',
                                    emptyText: 'Pilih anak dari',
                                    enableKeyEvents: true,
                                    anyMatch: true,
                                    displayField: 'jabatan_nama',
                                    forceSelection: true,
                                    minChars: 1,
                                    pageSize: 15,
                                    store: 'Sipas.jabatan.Combo',
                                    typeAhead: true,
                                    valueField: 'jabatan_id'
                                },
                                {
                                    xtype: 'sipas_com_button_cross'
                                }
                            ]
                        },
                        {
                            xtype: 'combobox',
                            bootstrapProperty: 'Sipas.unit.Prop',
                            associated: true,
                            anchor: '100%',
                            fieldLabel: 'Unit Kerja',
                            name: 'jabatan_unit',
                            emptyText: 'Pilih unit kerja',
                            enableKeyEvents: true,
                            anyMatch: true,
                            displayField: 'unit_display',
                            forceSelection: true,
                            minChars: 1,
                            pageSize: 15,
                            store: 'Sipas.unit.Combo',
                            typeAhead: true,
                            valueField: 'unit_id'
                        },
                        {
                            xtype: 'fieldset',
                            languageable: true,
                            languageCode: 'kode_eselon',
                            languageMode: 'text',
                            padding: 0,
                            title: 'Kode Eselon',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    name: 'jabatan_isnomor',
                                    boxLabel: 'Jabatan mempunyai kode eselon dan dapat mengeluarkan nomor surat',
                                    inputValue: '1'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            languageable: true,
                            languageCode: 'jabatan_ispenerima',
                            languageMode: 'text',
                            padding: 0,
                            title: 'Sebagai Penerima',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    languageable: true,
                                    languageMode: 'boxLabel',
                                    languageCode: 'jabatan_ispenerima_boxlabel',
                                    anchor: '100%',
                                    name: 'jabatan_ispenerima',
                                    boxLabel: 'Jabatan dapat menjadi penerima surat',
                                    inputValue: '1'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldset',
                            padding: 0,
                            title: 'Status Aktif',
                            items: [
                                {
                                    xtype: 'checkboxfield',
                                    anchor: '100%',
                                    name: 'jabatan_isaktif',
                                    boxLabel: 'Aktif',
                                    inputValue: '1'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'container',
                    dock: 'bottom',
                    itemId: 'toolbarAction',
                    ui: 'footer',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_delete',
                            roleName: 'jabatan_delete',
                            roleable: true
                        },
                        {
                            xtype: 'button',
                            languageMode: 'title',
                            languageCode: 'pegawai_list',
                            languageable: true,
                            itemId: 'btnStafJabatan',
                            text: 'DAFTAR pEGAWAI'
                        },
                        {
                            xtype: 'button',
                            roleable: true,
                            roleName: 'unitkerja_kewenangan',
                            languageCode: 'unit_kerja_kewenangan_list',
                            languageMode: 'text',
                            languageable: true,
                            featureable: true,
                            featureName: 'unit_cakupan',
                            itemId: 'btnUnit',
                            text: 'DAftar unit Cakupan'
                        },
                        {
                            xtype: 'sipas_com_button_edit',
                            roleName: 'jabatan_update',
                            roleable: true
                        },
                        {
                            xtype: 'sipas_com_button_save'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});