/*
 * File: app/view/Sipas/jabatan/tim/Compact.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.jabatan.tim.Compact', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sipas_jabatan_tim_compact',

    requires: [
        'SIPAS.view.Sipas.jabatan.tim.List',
        'SIPAS.view.Sipas.jabatan.tim.anggota.Form',
        'Ext.grid.Panel',
        'Ext.form.Panel'
    ],

    languageCode: 'kelompok_jabatan_list',
    languageMode: 'title',
    languageable: true,
    layout: 'border',
    bodyBorder: false,
    title: 'Daftar Kelompok Jabatan',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'sipas_jabatan_tim_list',
                    dbclickToView: true,
                    clickToView: false,
                    border: false,
                    header: false,
                    region: 'center'
                },
                {
                    xtype: 'sipas_jabatan_tim_anggota_form',
                    disabled: true,
                    width: 480,
                    collapseDirection: 'right',
                    header: false,
                    region: 'east',
                    split: true
                }
            ]
        });

        me.callParent(arguments);
    }

});