/*
 * File: app/view/Sipas/arsip/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.arsip.Pane', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sipas_arsip_pane',

    requires: [
        'SIPAS.view.Sipas.arsip.Dataview',
        'SIPAS.view.Sipas.com.button.View',
        'SIPAS.view.Sipas.com.button.Refresh',
        'SIPAS.view.Sipas.com.button.Download',
        'Ext.view.View',
        'Ext.toolbar.Toolbar',
        'Ext.form.field.Display',
        'Ext.toolbar.Fill',
        'Ext.menu.Menu',
        'Ext.form.Panel',
        'Ext.form.field.File',
        'Ext.form.field.FileButton',
        'Ext.menu.Separator',
        'Ext.toolbar.TextItem'
    ],

    toolbarControl: true,
    border: false,
    cls: 'sipas_arsip_pane',
    minWidth: 180,
    layout: 'fit',
    header: false,
    title: 'Berkas',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                me.processSipasarsipdataview({
                    xtype: 'sipas_arsip_dataview',
                    viewConfig: {
                        preserveScrollOnRefresh: true
                    }
                }),
                {
                    xtype: 'button',
                    hidden: true,
                    itemId: 'buttonMenuArsip',
                    arrowCls: 'arrow_hidden',
                    menu: {
                        xtype: 'menu',
                        showSeparator: false,
                        items: [
                            {
                                xtype: 'menuitem',
                                action: 'open',
                                itemId: 'buttonOpen',
                                iconCls: 'icon ion-md-search blue-500-i',
                                text: 'Buka'
                            },
                            {
                                xtype: 'menuitem',
                                action: 'download',
                                languageable: true,
                                languageMode: 'text',
                                languageCode: 'download_berkas',
                                itemId: 'buttonDownload',
                                iconCls: 'icon ion-md-download green-700-i',
                                text: 'Unduh'
                            },
                            {
                                xtype: 'menuitem',
                                action: 'delete',
                                itemId: 'buttonHapus',
                                iconCls: 'icon ion-md-trash',
                                text: 'Hapus'
                            },
                            {
                                xtype: 'menuseparator',
                                itemId: 'berkasSeparator'
                            },
                            {
                                xtype: 'menuitem',
                                action: 'edit',
                                itemId: 'buttonEdit',
                                iconCls: 'icon ion-md-list-box orange-700-i',
                                text: 'Perubahan'
                            },
                            {
                                xtype: 'menuitem',
                                action: 'log',
                                itemId: 'buttonHistory',
                                iconCls: 'icon ion-md-menu blue-700-i',
                                text: 'Riwayat Perubahan'
                            }
                        ]
                    }
                }
            ],
            dockedItems: [
                me.processToolbarControl({
                    xtype: 'toolbar',
                    dock: 'top',
                    itemId: 'toolbarControl',
                    padding: 0,
                    items: [
                        {
                            xtype: 'displayfield',
                            margins: '0 0 0 16',
                            value: '<b style="color:#04408c">Berkas</b>'
                        },
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            cls: 'x-btn-info x-btn-circle',
                            itemId: 'buttonAdd',
                            arrowCls: 'arrow-down',
                            iconCls: 'icon ion-md-add-circle',
                            menu: {
                                xtype: 'menu',
                                showSeparator: false,
                                items: [
                                    {
                                        xtype: 'menuitem',
                                        action: 'upload',
                                        hidden: true,
                                        text: 'Unggah Berkas'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        action: 'upload_scan',
                                        languageable: true,
                                        languageMode: 'text',
                                        languageCode: 'upload_berkas_button_pane',
                                        iconCls: 'icon ion-md-folder amber-700-i',
                                        text: 'Unggah Dokumen'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        action: 'scan_image',
                                        scanFormat: 'jpg',
                                        hidden: true,
                                        text: 'Pindai Gambar'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        action: 'scan_pdf',
                                        scanFormat: 'pdf',
                                        hidden: true,
                                        text: 'Pindai PDF'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        action: 'link',
                                        languageCode: 'tautan_button_pane',
                                        languageMode: 'text',
                                        languageable: true,
                                        featureName: 'berkas_link',
                                        featureable: true,
                                        iconCls: 'icon ion-md-link',
                                        text: 'Tautan'
                                    },
                                    {
                                        xtype: 'menuitem',
                                        action: 'sdoc',
                                        featureName: 'berkas_sdoc',
                                        featureable: true,
                                        iconCls: 'icon ion-md-paper blue-700-i',
                                        text: 'Online Dokumen'
                                    }
                                ]
                            }
                        },
                        me.processView({
                            xtype: 'sipas_com_button_view',
                            action: 'showall',
                            hidden: true,
                            text: ' ',
                            tooltip: 'Lihat'
                        }),
                        me.processRefresh({
                            xtype: 'sipas_com_button_refresh',
                            action: 'reload',
                            cls: 'x-btn-primary x-btn-circle',
                            itemId: 'buttonRefresh',
                            iconCls: 'icon ion-md-refresh',
                            text: ' ',
                            tooltip: 'Muat Ulang'
                        }),
                        {
                            xtype: 'form',
                            border: 0,
                            hidden: true,
                            itemId: 'formUpload',
                            ui: 'footer',
                            layout: 'fit',
                            bodyBorder: false,
                            title: '',
                            items: [
                                {
                                    xtype: 'filefield',
                                    itemId: 'fileUpload',
                                    fieldLabel: '',
                                    hideLabel: true,
                                    name: 'userfile',
                                    enableKeyEvents: true,
                                    buttonOnly: true,
                                    buttonText: 'Upload Berkas',
                                    buttonConfig: {
                                        xtype: 'filebutton',
                                        text: 'Unggah'
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'sipas_com_button_download',
                            disabled: true,
                            hidden: true,
                            text: ' ',
                            tooltip: 'Unduh'
                        },
                        {
                            xtype: 'button',
                            hidden: true,
                            itemId: 'buttonViewAll',
                            text: 'Lihat Semua Berkas'
                        }
                    ]
                }),
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'tbtext',
                            hidden: true,
                            text: 'Unggah hanya untuk file <b>.doc</b>, <b>.docx</b>, <b>.xls</b>, <b>.xlsx</b>, <b>.pdf</b>, <b>.ppt</b>, <b>.pps</b>,<br/><b>.pptx</b>, <b>.zip</b>, <b>.rar</b>, <b>.7z</b>, <b>.gif</b>, <b>.jpg</b>, <b>.jpeg</b>, <b>.bmp</b> dan <b>.png</b>'
                        },
                        {
                            xtype: 'displayfield',
                            hidden: true,
                            value: '<b>*</b> Klik <b>2x</b> untuk <b>Melihat</b>'
                        },
                        {
                            xtype: 'displayfield',
                            languageable: true,
                            languageCode: 'berkas_reupload_warning',
                            languageMode: 'value',
                            cls: 'x-field-boxed x-field-boxed-warning',
                            itemId: 'reuploadWarning',
                            margin: '0 0 8 0',
                            width: '100%'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processSipasarsipdataview: function(config) {
        Ext.apply(config, this.dataviewConfig);
        return config;
    },

    processView: function(config) {
        config.text = null;
        return config;
    },

    processRefresh: function(config) {
        config.text = null;
        return config;
    },

    processToolbarControl: function(config) {
        if(!this.toolbarControl)
        {
            return null;
        }
        return config;
    }

});