/*
 * File: app/view/Sipas/klise/Compact.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.klise.Compact', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sipas_klise_compact',

    requires: [
        'SIPAS.view.Sipas.klise.List',
        'SIPAS.view.Sipas.klise.preview.Pane',
        'Ext.grid.Panel'
    ],

    languageable: true,
    languageMode: 'title',
    languageCode: 'template_list',
    border: 0,
    layout: 'border',
    title: 'Daftar Template Surat',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'sipas_klise_list',
                    width: 450,
                    header: false,
                    region: 'west'
                },
                {
                    xtype: 'sipas_klise_preview_pane',
                    cls: 'paper',
                    frame: true,
                    region: 'center',
                    split: true
                }
            ]
        });

        me.callParent(arguments);
    }

});