/*
 * File: app/view/Sipas/sla/unit/Form.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.sla.unit.Form', {
    extend: 'Ext.form.Panel',
    alias: 'widget.sipas_sla_unit_form',

    requires: [
        'SIPAS.view.Sipas.sla.unit.List',
        'SIPAS.view.Sipas.com.button.Save',
        'Ext.form.field.Hidden',
        'Ext.form.field.Text',
        'Ext.grid.Panel',
        'Ext.toolbar.Toolbar',
        'Ext.button.Button'
    ],

    border: false,
    bodyBorder: false,
    bodyPadding: '8 16 8 16',
    title: 'Unit Kerja',

    layout: {
        type: 'vbox',
        align: 'stretch'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'hiddenfield',
                    flex: 1,
                    fieldLabel: 'Label',
                    name: 'unit_id'
                },
                {
                    xtype: 'textfield',
                    fieldLabel: 'Unit',
                    name: 'unit_nama',
                    readOnly: true
                },
                {
                    xtype: 'sipas_sla_unit_list',
                    flex: 1
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    flex: 1,
                    dock: 'bottom',
                    border: false,
                    style: 'background-color: white;',
                    ui: 'footer',
                    defaultButtonUI: 'default',
                    layout: {
                        type: 'hbox',
                        defaultMargins: {
                            top: 4,
                            right: 4,
                            bottom: 6,
                            left: 4
                        },
                        pack: 'end',
                        padding: 5
                    },
                    items: [
                        {
                            xtype: 'sipas_com_button_save',
                            roleable: true,
                            roleName: 'sla_unit_insert'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});