/*
 * File: app/view/Sipas/informasi/peubahan/Popup.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.informasi.peubahan.Popup', {
    extend: 'Ext.window.Window',
    alias: 'widget.sipas_informasi_perubahan_popup',

    height: 250,
    width: 400,
    title: 'Informasi Lisensi',
    maximizable: true,

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});