/*
 * File: app/model/Sipas/staf/Wakil.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.staf.Wakil', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field',
        'Ext.data.association.HasOne'
    ],
    uses: [
        'SIPAS.model.Sipas.Staf'
    ],

    idProperty: 'staf_wakil_id',

    proxy: {
        type: 'ajax',
        api: {
            create: 'server.php/sipas/staf_wakil/create',
            read: 'server.php/sipas/staf_wakil/read',
            update: 'server.php/sipas/staf_wakil/update',
            destroy: 'server.php/sipas/staf_wakil/destroy'
        },
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    fields: [
        {
            name: 'staf_wakil_id'
        },
        {
            name: 'staf_wakil_staf'
        },
        {
            name: 'staf_wakil_asisten'
        },
        {
            name: 'staf_wakil_asisten_nama'
        },
        {
            name: 'staf_wakil_asisten_unit_nama'
        },
        {
            name: 'staf_wakil_asisten_jabatan_nama'
        },
        {
            name: 'staf_wakil_asisten_status'
        },
        {
            name: 'staf_wakil_properti'
        },
        {
            name: 'staf_wakil_plt',
            type: 'boolean'
        },
        {
            name: 'staf_wakil_tgl_mulai',
            type: 'date'
        },
        {
            name: 'staf_wakil_tgl_selesai',
            type: 'date'
        },
        {
            name: 'staf_id'
        },
        {
            name: 'staf_kode'
        },
        {
            name: 'staf_nama'
        },
        {
            name: 'staf_status'
        },
        {
            name: 'jabatan_id'
        },
        {
            name: 'jabatan_nama'
        },
        {
            name: 'unit_id'
        },
        {
            name: 'unit_nama'
        },
        {
            name: 'staf_wakil_staf_nama'
        },
        {
            name: 'staf_wakil_staf_jabatan_nama'
        },
        {
            name: 'staf_wakil_staf_unit_nama'
        },
        {
            name: 'staf_wakil_konfirmasi_staf'
        },
        {
            name: 'staf_wakil_konfirmasi_staf_status',
            type: 'int'
        },
        {
            name: 'staf_wakil_konfirmasi_staf_tgl',
            type: 'date'
        },
        {
            name: 'staf_wakil_konfirmasi_asisten'
        },
        {
            name: 'staf_wakil_konfirmasi_asisten_status',
            type: 'int'
        },
        {
            name: 'staf_wakil_konfirmasi_asisten_tgl',
            type: 'date'
        }
    ],

    hasOne: [
        {
            model: 'SIPAS.model.Sipas.Staf',
            primaryKey: 'staf_id',
            foreignKey: 'staf_wakil_staf',
            getterName: 'getPegawai',
            setterName: 'setPegawai'
        },
        {
            model: 'SIPAS.model.Sipas.Staf',
            primaryKey: 'staf_id',
            foreignKey: 'staf_wakil_asisten',
            getterName: 'getAsisten',
            setterName: 'setAsisten'
        },
        {
            model: 'SIPAS.model.Sipas.Staf',
            primaryKey: 'staf_id',
            foreignKey: 'staf_wakil_staf',
            getterName: 'getAtasan',
            setterName: 'setAtasan'
        },
        {
            model: 'SIPAS.model.Sipas.Staf',
            primaryKey: 'staf_id',
            foreignKey: 'staf_wakil_asisten',
            getterName: 'getPgs',
            setterName: 'setPgs'
        }
    ]
});