/*
 * File: app/store/Sipas/surat/tipe/Combo.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.store.Sipas.surat.tipe.Combo', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.proxy.Memory',
        'Ext.data.reader.Json',
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'Sipas.surat.tipe.Combo',
            proxy: {
                type: 'memory',
                data: [
                    {
                        surat_tipe: 'surat_masuk_eks',
                        surat_nama: 'Surat Masuk Eksternal'
                    },
                    {
                        surat_tipe: 'surat_masuk_int',
                        surat_nama: 'Surat Masuk Internal'
                    },
                    {
                        surat_tipe: 'surat_keluar',
                        surat_nama: 'Surat Keluar'
                    },
                    {
                        surat_tipe: 'surat_edaran',
                        surat_nama: 'Surat Edaran'
                    },
                    {
                        surat_tipe: 'surat_telaah',
                        surat_nama: 'Telaahan Staf'
                    }
                ],
                reader: {
                    type: 'json'
                }
            },
            fields: [
                {
                    name: 'surat_tipe'
                },
                {
                    name: 'surat_nama'
                }
            ]
        }, cfg)]);
    }
});