/*
 * File: app/view/Sipas/unit/cakupan/Compact.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.unit.cakupan.Compact', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.sipas_unit_cakupan_compact',

    requires: [
        'SIPAS.view.Sipas.jabatan.Treelist',
        'SIPAS.view.Sipas.unit.cakupan.Form',
        'Ext.tree.Panel',
        'Ext.form.Panel'
    ],

    languageable: true,
    languageMode: 'title',
    languageCode: 'unit_kerja_kewenangan_list',
    layout: 'border',
    bodyBorder: false,
    title: 'Daftar Unit Kerja Kewenangan',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'sipas_jabatan_treelist',
                    dbclickToView: true,
                    clickToView: false,
                    border: 0,
                    header: false,
                    flex: 2,
                    region: 'center'
                },
                {
                    xtype: 'sipas_unit_cakupan_form',
                    border: 0,
                    disabled: true,
                    width: 480,
                    header: false,
                    region: 'east',
                    split: true
                }
            ]
        });

        me.callParent(arguments);
    }

});