/*
 * File: app/view/Sipas/user/note/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.user.note.Pane', {
    extend: 'Ext.panel.Panel',

    requires: [
        'SIPAS.view.Sipas.com.button.Check',
        'SIPAS.view.Sipas.com.button.Uncheck',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.RowNumberer',
        'Ext.grid.column.Boolean',
        'Ext.grid.column.Date',
        'Ext.grid.View',
        'Ext.toolbar.Paging'
    ],

    height: 500,
    itemId: 'paneHakaksesUserNote',
    width: 450,
    layout: 'fit',
    title: 'Catatan',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'top',
                    items: [
                        {
                            xtype: 'sipas_com_button_check',
                            disabled: true,
                            text: 'Tandai'
                        },
                        {
                            xtype: 'sipas_com_button_uncheck',
                            disabled: true
                        }
                    ]
                }
            ],
            items: [
                {
                    xtype: 'gridpanel',
                    header: false,
                    title: 'My Grid Panel',
                    store: 'Sipas.user.note.List',
                    columns: [
                        {
                            xtype: 'rownumberer'
                        },
                        {
                            xtype: 'booleancolumn',
                            filterable: true,
                            width: 40,
                            align: 'center',
                            dataIndex: 'user_note_status',
                            menuDisabled: true
                        },
                        {
                            xtype: 'datecolumn',
                            filterable: true,
                            width: 100,
                            dataIndex: 'user_note_date',
                            text: 'Waktu',
                            format: 'd-m-Y'
                        },
                        {
                            xtype: 'gridcolumn',
                            filterable: true,
                            dataIndex: 'user_note_text',
                            text: 'Catatan',
                            flex: 1
                        }
                    ],
                    dockedItems: [
                        {
                            xtype: 'pagingtoolbar',
                            dock: 'bottom',
                            width: 360,
                            displayInfo: true,
                            store: 'Sipas.user.note.List'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});