/*
 * File: app/model/Sipas/jabatan/Wakil.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.jabatan.Wakil', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.Field',
        'Ext.data.association.HasOne'
    ],
    uses: [
        'SIPAS.model.Sipas.Jabatan'
    ],

    idProperty: 'jabatan_wakil_id',

    proxy: {
        type: 'ajax',
        api: {
            create: 'server.php/sipas/jabatan_wakil/create',
            read: 'server.php/sipas/jabatan_wakil/read',
            update: 'server.php/sipas/jabatan_wakil/update',
            destroy: 'server.php/sipas/jabatan_wakil/destroy'
        },
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    fields: [
        {
            name: 'jabatan_wakil_id'
        },
        {
            name: 'jabatan_wakil_jabatan'
        },
        {
            name: 'jabatan_wakil_asisten'
        },
        {
            name: 'jabatan_wakil_properti'
        },
        {
            name: 'jabatan_wakil_jabatan_nama'
        },
        {
            name: 'jabatan_wakil_jabatan_kode'
        },
        {
            name: 'jabatan_wakil_jabatan_isaktif',
            type: 'boolean'
        },
        {
            name: 'jabatan_wakil_asisten_jabatan_nama'
        },
        {
            name: 'jabatan_wakil_asisten_jabatan_kode'
        },
        {
            name: 'jabatan_wakil_asisten_jabatan_isaktif',
            type: 'boolean'
        },
        {
            name: 'jabatan_id'
        },
        {
            name: 'jabatan_nama'
        },
        {
            name: 'jabatan_kode'
        },
        {
            name: 'jabatan_isaktif',
            type: 'boolean'
        }
    ],

    hasOne: [
        {
            model: 'SIPAS.model.Sipas.Jabatan',
            primaryKey: 'jabatan_id',
            foreignKey: 'jabatan_wakil_jabatan',
            getterName: 'getJabatan',
            setterName: 'setJabatan'
        },
        {
            model: 'SIPAS.model.Sipas.Jabatan',
            primaryKey: 'jabatan_id',
            foreignKey: 'jabatan_wakil_asisten',
            getterName: 'getAsisten',
            setterName: 'setAsisten'
        },
        {
            model: 'SIPAS.model.Sipas.Jabatan',
            primaryKey: 'jabatan_id',
            foreignKey: 'jabatan_wakil_jabatan',
            getterName: 'getAtasan',
            setterName: 'setAtasan'
        }
    ]
});