/*
 * File: app/view/Sipas/com/button/ToggleFilter.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.com.button.ToggleFilter', {
    extend: 'Ext.button.Button',
    alias: 'widget.sipas_com_button_togglefilter',

    cls: 'x-btn-circle x-btn-nobackgroundchangeover',
    hidden: true,
    enableToggle: true,
    iconCls: 'icon ion-md-search',
    text: 'toggle filter',

    initComponent: function() {
        var me = this;

        me.callParent(arguments);
    }

});