/*
 * File: app/view/Sipas/com/surat/Pane.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.view.Sipas.com.surat.Pane', {
    extend: 'Ext.form.FieldSet',
    alias: 'widget.sipas_com_surat_pane',

    requires: [
        'SIPAS.view.Sipas.com.button.View',
        'Ext.form.field.Display',
        'Ext.button.Button',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.toolbar.Toolbar',
        'Ext.toolbar.Fill',
        'Ext.form.Label'
    ],

    enableButtonView: true,
    cls: 'sipas_com_surat_pane',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            formConfig: {
                
            },
            items: [
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'displayfield',
                            flex: 1,
                            itemId: 'suratDetail'
                        },
                        {
                            xtype: 'container',
                            itemId: 'lihatSurat',
                            layout: {
                                type: 'hbox',
                                align: 'bottom',
                                pack: 'end'
                            },
                            items: [
                                {
                                    xtype: 'sipas_com_button_view',
                                    roleable: true,
                                    roleName: 'surat_internal_masuk_lihat',
                                    ui: 'default-toolbar',
                                    text: 'Lihat Surat',
                                    margins: '4 4 8 4'
                                },
                                me.processBtnMore({
                                    xtype: 'button',
                                    propType: 'default',
                                    featureable: true,
                                    featureName: 'surat_selesai',
                                    roleable: true,
                                    roleName: 'surat_masuk_penerima_selesai',
                                    margins: '4 4 8 4',
                                    cls: 'x-btn-bordered',
                                    itemId: 'btnMore',
                                    ui: 'default-toolbar',
                                    arrowCls: 'arrow-down',
                                    iconCls: 'icon ion-md-more',
                                    menuAlign: 'tr-br?',
                                    menu: {
                                        xtype: 'menu',
                                        width: 220,
                                        items: [
                                            {
                                                xtype: 'menuitem',
                                                languageable: true,
                                                languageCode: 'disposisi_selesai',
                                                languageMode: 'text',
                                                propType: 'default',
                                                action: 'show_history',
                                                featureable: true,
                                                featureName: 'surat_selesai',
                                                roleable: true,
                                                roleName: 'surat_masuk_penerima_selesai',
                                                itemId: 'btnSelesai',
                                                iconCls: 'icon ion-md-checkmark',
                                                text: 'Selesai'
                                            }
                                        ]
                                    }
                                })
                            ]
                        },
                        {
                            xtype: 'toolbar',
                            flex: 1,
                            hidden: true,
                            items: [
                                {
                                    xtype: 'displayfield',
                                    itemId: 'jenisSurat',
                                    name: 'surat_jenis_masuk'
                                },
                                {
                                    xtype: 'tbfill'
                                }
                            ]
                        },
                        {
                            xtype: 'container',
                            cls: 'suratImage',
                            height: 48,
                            hidden: true,
                            itemId: 'suratImage',
                            width: 48,
                            listeners: {
                                render: {
                                    fn: me.onSuratImageRender,
                                    scope: me
                                }
                            }
                        },
                        {
                            xtype: 'container',
                            constructor: function() {
                                this.callParent(arguments);
                                return Ext.applyIf(this,{
                                    form: new Ext.form.Basic(this)
                                });
                            },
                            flex: 1,
                            hidden: true,
                            itemId: 'suratData',
                            margin: '0 0 0 10',
                            defaults: {
                                margin: 0,
                                margins: 0,
                                padding: 0
                            },
                            items: [
                                {
                                    xtype: 'displayfield',
                                    renderer: function(value, displayField) {
                                        if(value){
                                            return '<strong>'+Ext.util.Format.ellipsis(value,49)+'</strong>';
                                        }else{
                                            return '<span style= "color: grey;">'+'Tidak Ada Perihal'+'</span>';
                                        }
                                    },
                                    hidden: true,
                                    name: 'surat_perihal'
                                },
                                {
                                    xtype: 'container',
                                    hidden: true,
                                    itemId: 'suratDisplay',
                                    layout: {
                                        type: 'hbox',
                                        align: 'stretch'
                                    },
                                    items: [
                                        {
                                            xtype: 'displayfield',
                                            renderer: function(value, displayField) {
                                                return Ext.util.Format.ellipsis(value,20);
                                            },
                                            margins: '0',
                                            itemId: 'suratPengirim',
                                            margin: 0,
                                            padding: 0,
                                            name: 'pengirim'
                                        },
                                        {
                                            xtype: 'label',
                                            margins: '0',
                                            margin: '0 5',
                                            padding: 0,
                                            text: '_'
                                        },
                                        {
                                            xtype: 'displayfield',
                                            renderer: function(value, displayField) {
                                                return Ext.util.Format.ellipsis(value,20);
                                            },
                                            margins: '0',
                                            margin: 0,
                                            padding: 0,
                                            name: 'surat_nomor'
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            defaults: {
                                                margin: 0,
                                                margins: 0,
                                                padding: 0
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    processBtnMore: function(config) {
        config.propType = this.propType;
        return config;
    },

    onSuratImageRender: function(component, eOpts) {
        Ext.create('Ext.tip.ToolTip',{
            target: component.getEl(),
            html: 'Keterangan Surat'
        });
    },

    constructor: function() {
        this.callParent(arguments);
        return Ext.applyIf(this,{
            form: new Ext.form.Basic(this)
        });
    }

});