/*
 * File: app/model/Sipas/sla/Rumus.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.sla.Rumus', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.association.HasOne'
    ],
    uses: [
        'SIPAS.model.Sipas.Sla'
    ],

    idProperty: 'sla_rumus_id',

    fields: [
        {
            name: 'sla_rumus_id'
        },
        {
            name: 'sla_rumus_sla'
        },
        {
            name: 'sla_rumus_formula'
        },
        {
            name: 'sla_rumus_nilai',
            type: 'int'
        },
        {
            name: 'sla_rumus_properti'
        },
        {
            name: 'sla_id'
        },
        {
            name: 'sla_nama'
        },
        {
            name: 'sla_properti'
        },
        {
            name: 'sla_rumus_properti_id'
        },
        {
            name: 'sla_rumus_properti_buat_tgl',
            type: 'date'
        },
        {
            name: 'sla_rumus_properti_pembuat_id'
        },
        {
            name: 'sla_rumus_properti_pembuat_kode'
        },
        {
            name: 'sla_rumus_properti_pembuat_nama'
        },
        {
            name: 'sla_rumus_properti_pembuat_unit'
        },
        {
            name: 'sla_rumus_properti_pembuat_unit_nama'
        },
        {
            name: 'sla_rumus_properti_pembuat_jabatan'
        },
        {
            name: 'sla_rumus_properti_pembuat_jabatan_nama'
        },
        {
            name: 'sla_rumus_properti_isubah'
        },
        {
            name: 'sla_rumus_properti_ubah_tgl',
            type: 'date'
        },
        {
            name: 'sla_rumus_properti_pengubah_id'
        },
        {
            name: 'sla_rumus_properti_pengubah_kode'
        },
        {
            name: 'sla_rumus_properti_pengubah_nama'
        },
        {
            name: 'sla_rumus_properti_pengubah_unit'
        },
        {
            name: 'sla_rumus_properti_pengubah_unit_nama'
        },
        {
            name: 'sla_rumus_properti_pengubah_jabatan'
        },
        {
            name: 'sla_rumus_properti_pengubah_jabatan_nama'
        },
        {
            name: 'sla_rumus_properti_ishapus'
        },
        {
            name: 'sla_rumus_properti_hapus_tgl',
            type: 'date'
        },
        {
            name: 'sla_rumus_properti_penghapus_id'
        },
        {
            name: 'sla_rumus_properti_penghapus_kode'
        },
        {
            name: 'sla_rumus_properti_penghapus_nama'
        },
        {
            name: 'sla_rumus_properti_penghapus_unit'
        },
        {
            name: 'sla_rumus_properti_penghapus_unit_nama'
        },
        {
            name: 'sla_rumus_properti_penghapus_jabatan'
        },
        {
            name: 'sla_rumus_properti_penghapus_jabatan_nama'
        },
        {
            name: 'sla_rumus_properti_ispulih'
        },
        {
            name: 'sla_rumus_properti_pulih_tgl',
            type: 'date'
        },
        {
            name: 'sla_rumus_properti_pemulih_id'
        },
        {
            name: 'sla_rumus_properti_pemulih_kode'
        },
        {
            name: 'sla_rumus_properti_pemulih_nama'
        },
        {
            name: 'sla_rumus_properti_pemulih_unit'
        },
        {
            name: 'sla_rumus_properti_pemulih_unit_nama'
        },
        {
            name: 'sla_rumus_properti_pemulih_jabatan'
        },
        {
            name: 'sla_rumus_properti_pemulih_jabatan_nama'
        },
        {
            name: 'sla_rumus_properti_data'
        },
        {
            name: 'sla_rumus_index',
            type: 'int'
        }
    ],

    proxy: {
        type: 'ajax',
        api: {
            create: 'server.php/sipas/sla_rumus/create',
            read: 'server.php/sipas/sla_rumus/read',
            update: 'server.php/sipas/sla_rumus/update',
            destroy: 'server.php/sipas/sla_rumus/destroy'
        },
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    hasOne: {
        model: 'SIPAS.model.Sipas.Sla',
        primaryKey: 'sla_id',
        foreignKey: 'sla_rumus_sla',
        getterName: 'getSLA',
        setterName: 'setSLA'
    }
});