/*
 * File: app/model/Sipas/sla/Unit.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SIPAS.model.Sipas.sla.Unit', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json',
        'Ext.data.association.HasOne',
        'Ext.data.Field'
    ],
    uses: [
        'SIPAS.model.Sipas.Sla'
    ],

    idProperty: 'sla_unit_id',

    proxy: {
        type: 'ajax',
        api: {
            create: 'server.php/sipas/sla_unit/create',
            read: 'server.php/sipas/sla_unit/read',
            update: 'server.php/sipas/sla_unit/update',
            destroy: 'server.php/sipas/sla_unit/destroy'
        },
        reader: {
            type: 'json',
            root: 'data'
        }
    },

    hasOne: {
        model: 'SIPAS.model.Sipas.Sla',
        primaryKey: 'sla_id',
        foreignKey: 'sla_unit_sla',
        getterName: 'getSLA',
        setterName: 'setSLA'
    },

    fields: [
        {
            name: 'sla_unit_id'
        },
        {
            name: 'sla_unit_sla'
        },
        {
            name: 'sla_unit_unit'
        },
        {
            name: 'sla_unit_properti'
        },
        {
            name: 'sla_id'
        },
        {
            name: 'sla_nama'
        },
        {
            name: 'sla_hasil'
        },
        {
            name: 'sla_kriteria'
        },
        {
            name: 'sla_isaktif'
        },
        {
            name: 'sla_properti'
        },
        {
            name: 'unit_id'
        },
        {
            name: 'unit_nama'
        },
        {
            name: 'unit_kode'
        },
        {
            name: 'unit_rubrik'
        },
        {
            name: 'unit_isaktif'
        },
        {
            name: 'unit_manager'
        },
        {
            name: 'unit_induk'
        },
        {
            name: 'unit_properti'
        },
        {
            name: 'sla_unit_default'
        }
    ]
});